### ISSUE TITLE
Service Marketplace

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1012]
**Is your feature request related to a problem? Please describe.**

Due to open service broker being to complicated for what we need and svc-cat being unmaintained, we need to look for a replacement. 

I started a GH discussion here: https://github.com/epinio/epinio/discussions/854 where I added some high level requirements. 

**Describe the solution you'd like**

~I think Crossplane (https://github.com/crossplane/crossplane) is the right option to move forward. The main issue that I see is that they are missing local databases that give a clean way to bind to the application. This can be solved by working with some partners to build a "Local Database Provider".~

@jimmykarily has provided a good alternative with https://github.com/epinio/epinio/discussions/1262

**Describe alternatives you've considered**
See discussion

**Comment by agracey** [comment]
I had an idea: 

If we end up using crossplane, it has a helm provider already built. The issue that I have with that provider is that it doesn't give any feedback to the platform on how to build the secret that gets mounted. This could likely be solved by using a composition of the helm provider with a provider we build that generates the right secrets to be consumed. 

We could also fork a limited number of helm charts from bitnami and reduce the configurability of them to ease maintenance.

**Comment by jimmykarily** [comment]
Useful explanation: https://blog.crossplane.io/crossplane-vs-cloud-infrastructure-addons/

**Comment by jimmykarily** [comment]
I pushed a bunch of go code that lists the XRs defined in XRDs (as describe on the second step above): https://github.com/jimmykarily/epinio-issue-1012-poc

**Comment by jimmykarily** [comment]
Postponing this a bit while we collect more information around Crossplane and how we want to use it. cc @agracey

**Comment by andreas-kupries** [comment]
@jimmykarily  Do we have more information on Crossplane now?

**Comment by jimmykarily** [comment]
If we decide to go with it, it will be something like this:

- Epinio discovers XRDs installed on the cluster
- Epinio presents the XRDs as a "marketplace" to the user
- Epinio provides commands to provision/delete services using the above XRDs

Epinio will not install or manage the Crossplane installation. We could come up with some "demo" XRD to create tests around it. Maybe something that can be used by users during development (some helm installed postgresql?).

If all the above is said and done, we won't have much of a marketplace to present because there aren't many XRDs available in public. Epinio users will only benefit if they or someone else creates some definitions for services.

With that in mind, I'm not sure if this is make it in the top priority list right now. I'll leave that to @agracey to plan it.

**Comment by andreas-kupries** [comment]
Ok, so the CLI would regain commands like

```
service market    # list xrds - "service classes"
service provision NAME XRD_NAME (XRD_PARAM...)
service unprovision NAME
```

This assumes that XRD's come with some kind of parameters you can set during provision, and that it is possible to query an XRD for such parameters. Type information maybe as well ?

Will be XRD based services be similar to the catalog based services we had before ? If so we may have to reintroduce the `service` interface type. As I suspect that the bind/unbind operations will need a different implementation, while we would like to keep the higher levels of the API server unaware of that.

The alternative would be to have the `(un)provision` commands not just create/delete the XRD service, but also manage a secret to hold the service location and credentials, like `service create|delete` do. I.e. manage a part which maps directly to what epinio currently uses for services.

---
Wrt priority, I am only asking at the moment because this is in our TODO right now.

**Comment by jimmykarily** [comment]
Created a story for a spike here: https://github.com/epinio/epinio/issues/1281

**Comment by jimmykarily** [comment]
Spike was done. Implementation happened here: #1332 . There are some improvements (e.g. #1359) but there is no reason to keep this epic open. Closing.
