### ISSUE TITLE
API: Support 'first message' authentication approach for WebSockets

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1118]
**Is your feature request related to a problem? Please describe.**
- The follows on from https://github.com/epinio/epinio/issues/871
- Unfortunately the cookie approach doesn't work as well as hoped. As the cookie comes from a separate domain it's counted as third party which are commonly blocked
- The final approach, and a good summary of the situation, is to try option 1 from https://websockets.readthedocs.io/en/latest/topics/authentication.html. 

**Describe the solution you'd like**
- There's a good breakdown on how this might work at https://devcenter.heroku.com/articles/websocket-security#authentication-authorization
- This includes adding verification information associated with the token such as user, ip of requesting client, etc

**Additional context**
- This would unblock the UI from showing application logs and eventually streaming events
- The other final option is to create an independent epinio ui backend which would proxy all http requests (including wss upgrade). I think eventually this is where we need to get to but it would require a large investment of time. So if this issue is a similar heavy investment we need to re-evaluate the two.

**Comment by jimmykarily** [comment]
Let's check if we can avoid implementing token based authentication and use the `username+password` combination as the first "auth" message. Otherwise, we are introducing a third authentication method (we already have basic auth and cookies) and we would probably have to move everything (e.g. the cli) to token based auth.

**Comment by manno** [comment]
If I understand correctly, sending an `Authorization` header with the websocket upgrade request is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#access_using_credentials_in_the_url).

How about an [approach with a second endpoint and a JWT token](https://www.linode.com/docs/guides/authenticating-over-websockets-with-jwt/):

* add another endpoint that issues JWT tokens using public/private key crypto. The server uses the private key to create a token. The token data contains a timestamp.
* the client uses basic auth or cookie authentication to get a JWT from the server
* the client initiates a websocket connection, sending the JWT in the [URL as a query param](https://faqs.ably.com/is-it-secure-to-send-the-access_token-as-part-of-the-websocket-url-query-params)
* the server can validate the request, because the token is signed with its own key
* the server can expire the token based on the timestamp
* no state needed in the server, unless we want to revoke tokens before they expire


More links:
* https://stackoverflow.com/questions/64934740/websocket-connection-with-authorization-header/65001506
* https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/4361358#4361358

**Comment by jimmykarily** [comment]
>     * the client initiates a websocket connection, sending the JWT in the [URL as a query param](https://faqs.ably.com/is-it-secure-to-send-the-access_token-as-part-of-the-websocket-url-query-params)

The tokens will then fly unencrypted. I think that's the reason why authentication happens using headers usually. I'm not sure if this is acceptable in this case for some reason.

**Comment by manno** [comment]
No the tokens will still be secured by https. We still upgrade a https connection to wss.

From the article I linked: 

> Connections default to being over TLS these days, so from the outside you can't access query params, nor can you access the contents of messages.

 

> Traditionally it was considered poor practice to have credentials in query params because URLs can get stored in places such as logs for proxies, browser history, etc. However, neither of those concerns apply to websockets (a browser won't keep history of the connections made by a page), and proxies do not have access to the URL when there is a TLS tunnel. This concern arose when non-TLS interactions were the default. For comparison, most OAuth flows result in an endpoint access being made with an access_token query param.

**Comment by richard-cox** [comment]
We've had this debate on a previous product. Query params over https should be safe in transit but readable at the target server level, for instance they could appear in logs that record https requests. Though at that level I guess private things like headers, body, etc could also be logged.

**Comment by jimmykarily** [comment]
I didn't know query params are also encrypted in transit. I'm happy with this plan then. We should be very careful with the websocket authentication. That is what we are going to use for the [shell to the app feature](#1098 ) as well, which gives access to a terminal directly.
