### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1136]
CI is failing since Friday 21/01/2022, should be fixed.

**Comment by ldevulder** [comment]
Seems to fail near the patching: https://github.com/epinio/epinio/runs/4915755261?check_suite_focus=true

**Comment by ldevulder** [comment]
Seems related to this PR: https://github.com/epinio/helm-charts/pull/68

**Comment by andreas-kupries** [comment]
@ldevulder @juadk 

I have to admit that I do not see the connection to the HC PR.

While I see this PR in the HC repo, it is not integrated with main.
And looking at epinio itself, the HC submodule is at https://github.com/epinio/helm-charts/pull/56, since last Tue.
Definitely not the 68, and also working.

What I see is that something switching to goreleaser was merged on Friday.
... I suspect https://github.com/epinio/epinio/pull/1128
Which is still marked as draft, not merged, yet I see the base commit from it in the history of main, plus 2 fixup commits and a commit changing a changelog section title.

I suspect that this should not have been put on main (yet).
I recommend reversion back to cd7d9a9328a97569b5e421282984582fd00315a7

@manno Any thoughts ?

**Comment by manno** [comment]
I can only test the CI in main. This is intended.

**Comment by andreas-kupries** [comment]
>I can only test the CI/release process in main. This is intended.
:ok_hand:

**Comment by ldevulder** [comment]
There was a remaining issue, fixed by here: https://github.com/epinio/helm-charts/pull/72
