### ISSUE TITLE
Upgrade checks for both server and CLI

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1153]
**Is your feature request related to a problem? Please describe.**

It would be very useful to let someone using the Epinio CLI to know that they should update their client when the server gets updated. It would also be useful to an admin to show when an update to Epinio as a whole can be upgraded.

**Describe the solution you'd like**

A MOTD-like output when there is a mismatch in client/server or an upgrade available to the server. This could also be shown in the UI as well. 

Extra points for a way to let the client update itself in-place.

**Comment by enrichman** [comment]
We can add an header with the version to every server response, so the CLI can check it and show the message eventually.

**Comment by jimmykarily** [comment]
I started working on this here: https://github.com/epinio/epinio/tree/1153-cli-check-new-version
The version mismatch warning is easy to implement. This is what I'm doing so far:

```
~/workspace/epinio/epinio (1153-cli-check-new-version)$ epinio app list

🚢  Listing applications
Namespace: workspace
2022/09/22 16:40:51 EpinioApiClient: "msg"="Epinio server version (v1.2.0-23-g11a2d241) doesn't match client version (v1.2.0-24-g933c0883)" "error"="version mismatch"

✔️  Epinio Applications:
| NAME | CREATED | STATUS | ROUTES | CONFIGURATIONS | STATUS DETAILS |
|------|---------|--------|--------|----------------|----------------|
```

This doesn't even need to compare the 2 versions and tell which one is older. It simply states the mismatch. I think this is ok since sometimes what you need is a downgrade of the client (e.g. when switching to an epinio instance that runs and older version).

Suggesting an upgrade of Epinio needs us to compare the current epinio-server version with the latest release. I think there are libraries that can compare semantic versions but this still poses some problems:

- When should that check happen? (keep in mind it involves some request to discover the latest Epinio release version)
- Who should be able to see this? (The epinio client doesn't have a concept of the user's role, it simply sends requests over to the server. Should it happen server side?)
- What versions do we compare? An upgrade may be needed if a new helm chart version is released, even if the server version is the same. On the other hand, if someone deploys Epinio manually, without helm (which is possible), the helm release version is no longer relevant.

In any case, warning about a full Epinio upgrade should be a separate issue. I will stick to the client "sync" for this issue and we can create another one for the full upgrade, if we decide we want it.

**Comment by jimmykarily** [comment]
There are 2 options on when to put the server version in a header:

1. Put it in every request (unauthenticated requests too)
2. Put it only in authenticated requests

Solution #1 can be considered bad from a security perspective because we are making the server version available to the world. In case it has a security issue, everyone will be able to tell.

Solution #2 will be  problem if the out-of-sync client is unable to login (e.g. because we changed how authentication works).

I'm not sure which one is worse.

**Comment by jimmykarily** [comment]
kuberlr is trying to handle the LinkError too: https://github.com/flavio/kuberlr/blob/master/internal/downloader/download.go#L195

let's see if we also need this

**Comment by gitricko** [comment]
haha, i think this is indeed useful as some of our engineers waste hours to figure out why thier cli/deployment not working.

In our CI/CD, we just run this command to ensure client and server are in sync
```
#Makefile
ep-ver-check:
	./scripts/makefile.sh ep-ver-check

# makefile.sh
function ep-ver-check {
	TMP_DIR=$(mktemp -d -t epinio.XXX)
	epinio info > ${TMP_DIR}/ep-version.txt
	cat ${TMP_DIR}/ep-version.txt
    SERVER_VER=$(cat ${TMP_DIR}/ep-version.txt | grep 'Server Version' | awk -F\: '{print $2}' | sed 's/[[:alpha:]]//g' | sed 's/[[:space:]]//g')
    CLIENT_VER=$(cat ${TMP_DIR}/ep-version.txt | grep 'Client Version' | awk -F\: '{print $2}' | sed 's/[[:alpha:]]//g' | sed 's/[[:space:]]//g')
    if [ ${SERVER_VER} != ${CLIENT_VER} ]; then
        echo "$SERVER_VER != $CLIENT_VER"
        exit 1
    fi
}



```

**Comment by jimmykarily** [comment]
I solved the Windows error by first moving the running binary and then copying the new binary to the original location: https://github.com/epinio/epinio/commit/f57180b984e6b1f5b40b8d625b5cd57e075b02da#diff-4e6707db4f2615e4e307ba0ef9616f5adf2999a9209b27f19e2de60d536b7513R57-R68

Windows are fine with that. The only problem is that I can't delete the running binary (I can only move it), but I moved it to a tmp directory so it's up to the OS to clean it up. I've read Windows are not very good in cleaning up tmp directories but that's the best solution I could find.

**Comment by andreas-kupries** [comment]
How about naming the old binary in the tmp directory in a distinctive way ?
Then, when the user uses the new binary, let it look in tmp for its old copy and remove it.

**Comment by jimmykarily** [comment]
> 



> How about naming the old binary in the tmp directory in a distinctive way ? Then, when the user uses the new binary, let it look in tmp for its old copy and remove it.

that's #3 also suggests here: https://github.com/restic/restic/issues/2248#issuecomment-903872651 . I'm not sure even invocation of the binary should try to cleanup old binaries. This is an operation that could fail for many reasons and it would render the binary unusable until fixed.

**Comment by andreas-kupries** [comment]
Ignore failures in the cleanup ?

**Comment by jimmykarily** [comment]
I'd rather leave this to the OS to be honest. If the OS does its job, it should be fine.

**Comment by mmartin24** [comment]
Checked on branch on MacOS and working

<img width="612" alt="image" src="https://user-images.githubusercontent.com/37271841/193016462-0225c1de-0b04-44fd-aa61-c8bf48072d29.png">
