### ISSUE TITLE
Spike: Replace Traefik with an nginx ingress controller

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1178]
A lot of traefik-specific annotations in the helm chart and some more in the epinio api server. The ingress class is hardcoded to 'traefik'. Traefik is configured to do an automatic redirect from http to https.

* https://github.com/epinio/epinio/issues/382
* https://github.com/epinio/epinio/issues/384
* https://github.com/epinio/epinio/issues/522

Can we ignore the traefik annotations and add some more to make it work with nginx? Would it work with other ingresses? The [ingress class annotation is deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation), should we update?

**Comment by agracey** [comment]
A few thoughts:

- In general, we should default to K8s native objects instead of traefik/nginx specific ones
- In the helm chart, we should flip the default, so all of the components other than epinio and kubed are optional
- - We *should* keep the dependencies as subcharts with the option to enable for those not on K3s or RKE2
- - Can helm "fail fast" if dependencies are not met or would not be met after installation?
- The ingress annotations of the control plane Ingress object (epinio itself) could be customized via the helm chart
- The class and annotations of app Ingresses should likely just be k8s defaults until we have a way to [customize the app definition](https://github.com/epinio/epinio/issues/361)
- - We should still set up https and a CertificateRequest when we see the CRD present

**Comment by ldevulder** [comment]
Question: by default `ingressClassName` is empty, so the default installation behavior is still the same? Or for example on K3s do we have to set `--set ingressClassName=traefik`?

**Comment by manno** [comment]
> Question: by default `ingressClassName` is empty, so the default installation behavior is still the same? Or for example on K3s do we have to set `--set ingressClassName=traefik`?

The default behavior changed. The traefik annotations are dropped from the ingresses. However, in my experiment with k3s, traefik would still serve the ingresses:

> [If the parameter is set, only Ingresses containing an annotation with the same value are processed. Otherwise, Ingresses missing the annotation, having an empty value, or the value traefik are processed.](https://doc.traefik.io/traefik/providers/kubernetes-ingress/#ingressclass)

**Comment by andreas-kupries** [comment]
Done with #1203
