### ISSUE TITLE
Add release-drafter to main branch, so we can see a draft release

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1223]

**Comment by olblak** [comment]
I propose to run release-drafter each time a commit is pushed on Epinio main branches instead of "on tag creation".
This would allow us to easily see the content of the next release just by looking at the draft release. 
Release drafter can also decide using pull request label and semantic versioning rules the next release version.

when we published a "draft" release to pre-release or release, GitHub automatically creates the tag associated with the release which means that each time we want to release a new version, we just have to visit https://github.com/epinio/epinio/releases and with the correct permission we can trigger the release process.
