### ISSUE TITLE
Add questions.yaml (the rancher UI one) to the single chart

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1247]
We used to have a questions.yaml in the epinio-installer chart. This makes the UX better in Rancher because the user doesn't edit the yaml directly but gets UI controls for the various fields.

Let's add questions.yaml for the single chart too.

**Comment by juadk** [comment]
I have a first version of the file, however, due to hard-coded things, deployment only works with:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/6025636/156341207-adbff620-a09d-4281-8e99-52b616faee8b.png">
Namespace must be epinio (we know it already) but deployment name must also be epinio, otherwise, a random name is generated and something is miss-configured then.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/6025636/156342637-b658abaa-7bef-4f8b-97cb-fa17b50d25dd.png">
