### ISSUE TITLE
Installation should be idempotent

### ISSUE THREAD

**Issue by rohitsakala** [epinio/epinio#125]
Right now, if we run the install command twice, then carrier cli would give an error. Instead it should print "Already installed".

**Comment by jimmykarily** [comment]
The installer should fail on the first try. If it doesn't we should fix the original problem and not implement a workaround.
Being able to tell which component is already installed is a feature that will have it's own bugs and is probably very hard to get right. I think we should focus on making the installer stable and always working rather than working on workarounds for when the installer fails.

@rohitsakala agreed during planning. Closing.
