### ISSUE TITLE
Add a more reliable dev environment

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1346]
All the local development process is relying on having the correct tools installed. You need to have the same and correct version of Go, ginkgo, helm and so on. Also while developing the new CRD in the https://github.com/epinio/application repo we had to install `kubebuilder` and other tools like `controller-gen` that is not even clear how to get it. All of this hoping to have the same versions of everyone else.

We should rely on a different process, developing, building and testing within docker containers, to have all the same tools, same versions and reproducible build and process. This will probably benefit also the process structure, removing lots of tools scripts.

**Comment by jimmykarily** [comment]
Relevant: https://github.com/epinio/epinio/issues/1295

**Comment by jimmykarily** [comment]
Can we base this no rootless container so we don't mess up file permission with every build? Podman for example?

**Comment by gitricko** [comment]
In my project, i have the same issues and this is how i resolve this.

- Use (/misused) miniconda to create local environment as much as possible. conda even allows you to install non-python binaries like npm, java and even go. So every engineers can re-create this environment locally even for jenkins
- Use brew.sh for those we can install via miniconda

This work well for my projects. In fact, in CF deployment... i am using miniconda buildpack so that i get dev-prod parity between local env setup vs deployed setup.

Hope this helps.  My 5 cents...

**Comment by enrichman** [comment]
We kept the tools-install and made it simpler: https://github.com/epinio/epinio/blob/main/scripts/tools-install.sh
