### ISSUE TITLE
We should allow for a basic AuthZ 

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1375]
**Is your feature request related to a problem? Please describe.**
We should be able to partition users across multiple namespaces. 

**Describe the solution you'd like**

I think a good baseline here would be:
- [x] Users can be admin or not
- [x] Non-admin users can only list, push, update, and delete apps on a namespace that they are included in
- [x] Non-admin users can only list, push, update, and delete services on a namespace that they are included in
- [x] Non-admin users cannot run any commands that update system configuration. (I don't think we have any yet but just future proofing the reqs)
- [x] Admin users can do anything they want 
- [x] Users cannot target namespaces they don't own (fail fast)

**Comment by richard-cox** [comment]
When implementing this we should keep in mind that at some point 
- The UI will need to understand the abilities of the user in order to show/hide functionality. This means the API will need to reveal which resources are visible, also what can be done generally (create, list) or to specific resources (edit, delete).
- Some time in the much further future the UI should be able to manage users (create, list, etc) and their roles/permissions

**Comment by jimmykarily** [comment]
Create a first Spike story for this: https://github.com/epinio/epinio/issues/1389

**Comment by jimmykarily** [comment]
The spike is done, only this is not implemented:

```
 Users cannot target namespaces they don't own (fail fast)
```

we didn't "fail fast" so far. The user can target a non existing namespace and all that does is update the `settings.yaml` file locally.
I'll keep this story open to implement a "target" endpoint that checks:

- if the namespace exists (otherwise 404)
- if the user is allowed to access it (otherwise 401 or 404)

**Comment by enrichman** [comment]
@jimmykarily we have the `GET /namespaces/:namespace` endpoint. We could use that.
The only missing part would be checking the existance of the namespace, because we are using a middleware for the authorization, so if the user is trying to access a non-existing namespace we are returning a 401.

**Comment by enrichman** [comment]
Thinking a bit about this.. the easiest thing to do is probably use another middleware before the authorization, that will validate the existance of the namespace, moving the logic that is now handled by the controllers.

This will block the client with an appropriate `404` in case of a missing namespace, and will fall through the authorization if it exists.

We should probably also change the status code and return a `403`, that is more correct.

**Comment by enrichman** [comment]
With the last PR we can close this.
