### ISSUE TITLE
End-to-end tests of UI

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1381]
We should test pushing an application via the UI in the e2e tests.

**Comment by juadk** [comment]
We already test all the features included in the Rancher UI (https://github.com/epinio/epinio-end-to-end-tests).
<img width="858" alt="image" src="https://user-images.githubusercontent.com/6025636/164676017-7f692738-98c5-492f-96a7-5b57e479e6db.png">

The missing thing is that we cannot execute those test suites on the Standalone UI due to https://github.com/epinio/ui/issues/88

I think this issue can be closed.

**Comment by juadk** [comment]
I'm closing this issue, feel free to re-open if I misunderstood your request.
