### ISSUE TITLE
"service" list/show endpoints should return bound applications too

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1450]
To avoid too many requests against the kube api, consider caching the information on the helmchart CRD (annotation or label?)
We need to keep this updated, e.g. every time an application is bound/unbound/deleted/etc

Investigate if labels or annotations are betters, one of them may trigger controllers and such.

**Comment by andreas-kupries** [comment]
First thoughts. @enrichman @jimmykarily 

We currently show bound apps with `configurations`.

The relevant functions are `application.BoundAppsNamesFor()` and `application.BoundAppsNames()` for show and list, respectively.

Both use a __single__ kube call to get the core information, i.e. the config binding resources, either for a single configuration, or for all configurations (in the namespace, or all namespaces). The call is always a `List` with proper selectors.

In the case for all configs the function returns a map the calling list endpoint can then use to add the information to each configuration in the result.

Now, at heart `service bindings` are `configuration bindings`. We should be able to reuse the machinery for them.
The main issue is translating from service name to the associated configuration name.

That is currently done by a search (list) for the secrets of the service and using all of them, in a loop. For each service.
While that loop is small doing it for each listed service ... That could be a source of slowness, if there are many services in a namespace. Caching this information as a label on the service itself might be useful.

Actually, if the `service create` call would wait for the service to deployed then the information could be added immediately instead of looked up and cached later.

That should simplify a number of other existing places also, i.e. un/binding. These are the places currently doing the search loop to go from service to configuration(s)/secret(s).

I will now go and deploy me some local services to look and refresh my understanding of the existing labels on these.

**Comment by enrichman** [comment]
I just want to point out that labels are not meant to store data, and they're particularly strict about the values:

**Comment by enrichman** [comment]
I just want to point out that labels are not meant to store data, and they're particularly strict about the values ([labels/#syntax-and-character-set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)) :

- must be 63 characters or less (can be empty),
- unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
- could contain dashes (-), underscores (_), dots (.), and alphanumerics between.

If we have a many-to-many relationship between resources it's not possible to use them.

How would you track for a binding between configurations and apps, since an app could have multiple configurations and a configuration multiple apps?

**Comment by andreas-kupries** [comment]
> How would you track for a binding between configurations and apps, since an app could have multiple configurations and a configuration multiple apps?

AFAIK we are already tracking this. See `application.BoundAppsNamesFor()` and `application.BoundAppsNames()`. Reusing that information is the point of my thoughts.

**Comment by andreas-kupries** [comment]
@enrichman 

Aha ... I found the place where we store the tracking information (again) ...
For each app X it is the `X-svc-...` secret.
It contains the name of each bound configuration as a data key of the secret.
(It seems I have found a place missed in the `service` :arrow_right: `configuration` renaming)

Example:

```
apiVersion: v1
data:
  x7a3b5458633936bc60aebbf9c27c-redis: ""
metadata:
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/name: fox
    app.kubernetes.io/part-of: workspace
    epinio.suse.org/area: configuration
...
```

The `application.BoundAppsNames*` functions list these `binding` secrets in a single call and then pull the information about configurations out.

Nothing with labels, nor annotations, except to simplify getting only the relevant secrets (selector `epinio.suse.org/area=configuration`.

We can use the same schema for services.
Or we could try to cache the service/config mapping (1:n) and then reuse the config information.

**Comment by andreas-kupries** [comment]
Thinking, the first, while duplicating config machinery for services is likely better because speed, the other would have 2 stages to get the information, i.e. likely slower.

I will then fix the `-svc-` part of the config machinery as part of this.
