### ISSUE TITLE
Add additional information to service catalog resource type

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#1463]
In order to support a more visually interesting experience in the UI can the following properties be helm chart properties be passed through to the UI via epinio API?

- url of the chart's icon
- version of the chart it will installed

**Comment by jimmykarily** [comment]
Helm charts already have an `icon` field in the Chart.yaml. To avoid parsing the chart tarball to find it, we can ask the operator to set that field on our `services.application.epinio.io` CRD

**Comment by enrichman** [comment]
It's a bit annoying to ask this to the operator, since it's an information that we can retrieve, and maybe in the future we will need other things to add.

The `index.yaml` from the Helm repo contains everything, but it could be too much to fetch just for a field (the bitnami one is 14Mb: https://charts.bitnami.com/bitnami/index.yaml ). The `helm show chart` command is what we need, but can we use it? I have not found a way with the client that we are using.

```bash
-> % helm show chart epinio/epinio 
annotations:
  artifacthub.io/license: Apache-2.0
apiVersion: v2
appVersion: v0.8.0
dependencies:
- condition: minio.enabled, global.minio.enabled
  name: minio
  repository: https://charts.min.io/
  tags:
  - minio
  version: 4.0.2
- condition: kubed.enabled, global.kubed.enabled
  name: kubed
  repository: https://charts.appscode.com/stable/
  tags:
  - kubed
  version: 0.13.2
- condition: epinio-ui.enabled
  name: epinio-ui
  repository: https://epinio.github.io/helm-charts
  tags:
  - epinio-ui
  version: 0.3.2
description: The official way to install Epinio
home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
maintainers:
- email: team@epinio.io
  name: SUSE
name: epinio
sources:
- https://github.com/epinio/epinio
version: 0.10.0

```

**Comment by jimmykarily** [comment]
Regarding the version information in the description above, the API already returns these fields:

```
    "chartVersion": "9.0.5",
    "appVersion": "3.9.17",
```
(these are from the `rabbitmq-dev` catalog service)

**Comment by jimmykarily** [comment]
The catalog service version information may or may not be present. Epinio's built-in catalog services do have these fields but custom catalog service created by operators may not. We should document the requirement for these fields so that catalog service are presented in a nice way in the UI (and cli).

**Comment by jimmykarily** [comment]
I tried to add a ShowChart function to the go-helm-client and use that to fetch the icon: https://github.com/epinio/epinio/commit/55f3a2054c369fcc6394d3309827c6761f7a19f8

It feels hacky and complicated. I want to simply try to add a field to the catalog service CRD and let the operator populate it. We can document a command that can get the icon from the chart and update the CR in case the operators are lazy and want to simply copy the one from the chart.

Having it as a separate field allows the operators to use a different icon for the epinio UI from the one in the chart itself. This may be considered a feature.
