### ISSUE TITLE
Version mismatch between GUI and `epinio info`

### ISSUE THREAD

**Issue by jandubois** [epinio/epinio#1581]
For example with the epinio-0.9.0 helm chart `epinio info` reports server version 0.9.0 correctly, but the GUI claims to be 0.11.0.

The same thing happens with 1.0.0-rc2, where the GUI claims to be 1.0.0-rc1.

The GUI should report the version from the API and not have its own version baked in (at least I assume that is the issue here).

**Comment by jimmykarily** [comment]
At some point, we decided to show the  chart version in the UI because we thought that this should the be version the user should know (because it's the collection of all the things that make up Epinio). Then we changed our minds and reverted that change because the rest of the components are kind of optional and can be replaced by others or other versions.

On `1.0.0-rc2` it's correct, because the server version is still `rc1`. We didn't have to release another version of the binary because the fixes were only on the chart.

**Comment by jimmykarily** [comment]
This should be fixed in `v1.0.0`:

- https://github.com/epinio/epinio/releases/tag/v1.0.0
- https://github.com/epinio/helm-charts/releases/tag/epinio-1.0.0

**Comment by jimmykarily** [comment]
I'm closing this one since it's fixed. @richard-cox will create another story to change how we decide which version to show in the UI. Instead of [hardcoding that](https://github.com/epinio/helm-charts/blob/3954c214de3d7b957cfc2054ba4fa4bfa140f5a3/chart/epinio/values.yaml#L89) we will get if from the `/info` endpoint (like the `epinio info` command does).
