### ISSUE TITLE
admin password with special character does not work!

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#1608]
**Describe the bug**
Trying to create password with special character does not work. eg: `Hell@World`

**To Reproduce**
0. Use password hash from `htpasswd -bnBC 10 "" Hell@World| tr -d :`
1. Install Epinio via this command
```
	helm install epinio -n epinio --create-namespace epinio/epinio \
		--set global.domain=${DOMAIN} \
		--set global.tlsIssuer=letsencrypt-epinio \
		--set api.users[0].username=admin \
		--set api.users[0].passwordBcrypt='<enter_password_hash>' \
		--set api.users[0].role=admin \

```
3. Login to admin console with password `Hell@World`, it will fail
4. Generate password for `HelloWorld`
5. undeploy and redeploy epinio. 
6. Login with this password. It will work!

I have tried `@ and !`

**Expected behavior**
password with special characters should work

This was a nasty bug... as it turn me a few hours the issue was becos of epinio ;-)

**Comment by agracey** [comment]
@enrichman IIRC, you were looking at auth? This one may be worth a quick patch release if it's an easy fix.

**Comment by enrichman** [comment]
Sure thing 👍

**Comment by enrichman** [comment]
After an investigation I've found out the issue. It has due to a missing url decoding of the username/password.

I spent a bit having a look at the `ui-backend` code that does the proxying for the frontend, just to avoid to add a quick fix that was capable of other strange bugs.

It looks like we are escaping the username and password:

https://github.com/epinio/ui-backend/blob/57c64c5566e874648466845abb39142e9bdd4435/src/jetstream/authepinio.go#L188

```go
req.SetBasicAuth(url.QueryEscape(username), url.QueryEscape(password))
```

but looking at the comment of the `SetBasicAuth` this is not wrong:

```
// Some protocols may impose additional requirements on pre-escaping the
// username and password. For instance, when used with OAuth2, both arguments
// must be URL encoded first with url.QueryEscape.
```

so I think that we are fine on Unescape them again in Epinio. Let me fix this. :)
