### ISSUE TITLE
Allow providing a custom cert for the epinio registry

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1634]
**Is your feature request related to a problem? Please describe.**
According to the docs: https://docs.epinio.io/explanations/advanced#container-registry

By default pulls are unencrypted because epinio is not able to modify the CAs that the Kubernetes cluster trusts. In cases of Rancher deployments like RKE2, you are in control of the CAs that the host OS has. It would be nice if epinio allowed providing a custom cert, signed by your CA, for the built in registry. This would allow encrypted staging and pulls, solving the notice given in the document for that use case.

**Describe alternatives you've considered**
The alternative is to have an eternal registry.

**Comment by jimmykarily** [comment]
We've had various hacks to make the communication with the built-in registry encrypted in the past. Even then, there were cases in which the hacks didn't work. Since the internal registry was only used to make the default installation simple, we've concluded that it shouldn't be used in production environments and we should try to build too many features around it. So the hacks were removed and the suggestion now is (copying from the docs): 

```
If encryption is desired, the container registry should be installed manually and configured as an ["external" registry](https://docs.epinio.io/howtos/setup_external_registry) during Epinio installation.
```

Even if you want to run the registry inside the cluster, you can still configure it as an "external" registry and use any TLS certificate you've made sure is trusted.

Can we close this? Let us know if we are missing something.

**Comment by braunsonm** [comment]
Sure that's fine. I just figured this is the main thing that is called out in the docs as being an insecure default that Epinio installs with. Having the option to provide a certificate would solve that, but if the guidance is not to use it in production environments then maybe that should be called out in the docs, I didn't see that.

**Comment by jimmykarily** [comment]
Thinking again, using a custom certificate is possible with just a new value here: https://github.com/epinio/helm-charts/blob/5209e38daff17dbd676f068a8aae4f44f88652c1/chart/epinio/values.yaml#L96 and some modifications here: https://github.com/epinio/helm-charts/blob/main/chart/epinio/templates/container-registry.yaml

Regarding docs, you are right, they will need to be adapted in every case. And our defaults shouldn't be insecure but this is a tradeoff to make user's first installation easier.

**Comment by jimmykarily** [comment]
It turns out that it's not that simple ([look at the comments in the PR](https://github.com/epinio/helm-charts/pull/266)). `localhost` is treated as an insecure registry by default (at least the containerd runtime). This means, we need to expose the registry through an ingress (like we did in the past). The reason we removed the registry ingress in the first place was that the internal registry is more of a convenience than a production level supported registry.

Deploying a registry on the Kubernetes itself or using an existing remote one should be an easy task and Epinio helm chart already supports pointing to an external registry. I suggest we close this issue given the alternative is already documented: https://docs.epinio.io/howtos/setup_external_registry
