### ISSUE TITLE
Limit the ability to create namespaces

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1648]
**Is your feature request related to a problem? Please describe.**
As an operator, I do not want users to be able to create a namespace with any name since that translates to an actual namespace on the cluster. This free reign to name the namespace however they like can make it difficult to integrate with tools like Gatekeeper and apply policies to the workspaces you expect if users create namespaces and deploy apps in ones other than they are assigned to.

**Describe the solution you'd like**
More fine grained permissions controls to disallow namespace creation or apply a prefix to namespaces in Kubernetes for epinio based resources.

**Comment by enrichman** [comment]
Hi @braunsonm, would it be a workaround to add a policy that will restrict the creation of the Epinio namespace?

I was thinking about a Gatekeeper (or Kubewarden) policy that will check that the namespace create request coming from Epinio would satisfy your needs (such as having a common prefix like `epinio-`).
Or maybe we can think about adding a `created-by` label, so that would be possible on the operator side to do more fine grained controls.

**Comment by braunsonm** [comment]
Yea, specifically having a common prefix would help us. This would allow us to have Istio policies which support wildcards such as allowing egress only to `epinio-workloads-*` namespaces for example.

Or simply only allowing certain users to create namespaces so operators are in control of the ones being used.

**Comment by jimmykarily** [comment]
> Or simply only allowing certain users to create namespaces so operators are in control of the ones being used.

This would introduce roles and permissions which needs more thought (it's a big feature). If annotations or prefixes work for this case I would suggest we use those for now.

**Comment by jimmykarily** [comment]
We did some back and forth regarding how we name Epinio resources and it started becoming clear that it's better not to rely on names for lookups and filtering. Labels and annotations are better suited for things like that. Given `kubewarden`, `gatekeeper` and Istio policies were all mentioned in this issue,  would annotations/labels would work for all these, equally well to prefixes? If not then maybe we need consider prefixing again.

@braunsonm maybe you can answer for at least `gatekeeper` and Istio policies.

**Comment by jimmykarily** [comment]
Now that I think again, what I suggest doesn't make sense, does it? What would the policy block the creation on? The end goal is to prevent the user from creating namespaces with arbitrary names. The labels and annotations won't help.

**Comment by braunsonm** [comment]
Correct ya. So here's a usecase, I want to restrict epinio apps with istio so they can't talk internally with other things on the cluster. In istio you'd use a sidecar policy for this but it only matches on namespace name.

I need to make sure users can't just create any namespace and therefore bypass policies applied to it.

**Comment by andreas-kupries** [comment]
> Now that I think again, what I suggest doesn't make sense, does it? What would the policy block the creation on? The end goal is to prevent the user from creating namespaces with arbitrary names. The labels and annotations won't help.

Do not get to hung up on blocking ... Some of the examples read a bit like it would be enough for the tools (GateKeeper, Istio, ...) to be able to identify the namespaces which were created by epinio so that policies can be applied to them. Like restricting networking to other epinio-controlled namespaces.

Forcing a specific prefix on all epinio-controlled namespaces in some installation, or blocking users from creating new namespaces in said installation outright ... look both to be hackish means of identifying the namespaces of interest, either by matching on their names, or by having only a fixed set of namespaces outright.

Like for
> In istio [...] but it only matches on namespace name

which seems to tell me that Istio is not capable of selecting namespaces of interest by labels and/or annotations ?
Given that the ability to select kube resources by labels and annotations is (AFAIK) built in the kube client libraries already I do not understand why Istio would then not provide the same to its users. It looks to me to be a serious limitation in istio itself.

---

In the interest of avoiding an [XY problem](https://xyproblem.info/) the core of the request is the need to identify the namespaces under the control of Epinio, right ? To enable other tools to operate on exactly these namespaces ? And limitations in the tools force identification by namespace name ? Tools capable of identifying namespaces by labels (example: ) would not require this ticket ?

----

I wonder if we could get away without an kind of limitation system if we were to stop mapping an epinio namespace (EN) `foo` directly to a kube namespace (KN) `foo`. We could say that an EN `foo` is created as KN `epinio-foo`. At that point the ability to create namespaces does not have to be limited anymore at all.

**Comment by braunsonm** [comment]
@andreas-kupries Correct, the specific policy I'm talking about is egress rules on sidecars which use the `namespace/hostname` pattern for matching: https://istio.io/latest/docs/reference/config/networking/sidecar/#IstioEgressListener

I still think it is useful to have more robust access controls by not allowing arbitrary namespaces to be created in the cluster if that is what the operator chooses. I do not think we are running into XY problem territory here as I provided the reasoning for the request, but let me know if anything is still unclear.

**Comment by andreas-kupries** [comment]
See #1946 for epic with broader applicability
