### ISSUE TITLE
Linkerd is not created?

### ISSUE THREAD

**Issue by braunsonm** [epinio/epinio#1649]
**Describe the bug**
According to the docs, linkerd is used for mTLS communication in the cluster. I can't seem to find linkerd installed at all after running through the steps.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio
2. Notice linkerd is not installed and there is no mTLS

**Expected behavior**
Linkerd should be installed and mTLS established

**Comment by enrichman** [comment]
Hi @braunsonm, since [we removed many components](https://github.com/epinio/epinio/issues/1217) to simplify the installation we also removed the linkerd dependency, and the only internal communication (with minio) is done with a certificate issued by cert-manager. The doc should not mention `linkerd` anymore. If so it's a leftover.

**Comment by braunsonm** [comment]
Ah okay thank you @enrichman 
It is still in your README
