### ISSUE TITLE
App URL with a279f postfix (app-a279f.domain.com)

### ISSUE THREAD

**Issue by riqueps** [epinio/epinio#1698]
Every time I push an app, the app url is created with a postfix. eg: app-a279f.domain.com

Epinio version: 1.1.0
Environment: AWS EKS
Ingress: nginx

[Install epinio on EKS](https://docs.epinio.io/next/howtos/install_epinio_on_eks) to reproduce this behavior.

![image](https://user-images.githubusercontent.com/47371890/186765960-1f8cb895-3cc8-4f76-aca9-316f91bb221a.png)

**Comment by jimmykarily** [comment]
Hi @riqueps , the suffix is and md5 hash of the namespace and was added here: https://github.com/epinio/epinio/commit/7c265a578#diff-31f0dac3ead01690242c1b3b77aecaedbe6e597da094216d65f95da3d093cc4aR28 as part of [this Pull Request](https://github.com/epinio/epinio/pull/1640) (also check the relevant issue in the PR description). The suffix ensures:

- route uniqueness for applications of the same name which live in a different workspace so that users of different namespace can't use the same routes intentionally or non-intentionally
- no user can try to "hijack" the default epinio API url (again intentionally or non-intentionally)

In a real world scenario, the automatic route provided by Epinio would be used as a CNAME to point an actual domain to the application or a custom route would be used for the same purpose. 

What I'm not sure about, is why we didn't put the namespace "raw" in the route instead of a hash. That would make the url more readable and easier to remember. Maybe there was some limitation in what characters can be used in a url or something? @enrichman or @andreas-kupries ?

**Comment by enrichman** [comment]
@jimmykarily I don't think there was a particular reason, the only collision that I can think about is the one about distinguishing the app name from the namespace: `foo-bar-baz`.

At the beginning of the development the suffix was just a random string, something like other providers or kubernetes do.

**Comment by jimmykarily** [comment]
Maybe we can do something like: `appname.namespace.systemdomain` (separated with dots). With system domain being a wildcard one, this could work.

**Comment by riqueps** [comment]
> 

One thing that I didn't understand why is this start happening now?
Because I have others epinio installations (on eks and k3d) and all of them the route is created with the app name (eg: appname.domain.com).

Is there a way to force always create the route with the app name, and just put a postfix if the route name isn't available?

**Comment by jimmykarily** [comment]
This change was introduced in `1.1.0`. Are you sure the other installation are on that version? You need to push a new app for this to happen, old apps won't get updated (e.g. apps deployed when still on `1.0.0`).

The default application chart changed here: https://github.com/epinio/helm-charts/commit/cbb88ca for version `1.1.0`.

You can always set the routes manually with the `--route` flag of `epinio push`.
We could maybe add the suffix only when there is a conflict but [there is more validation happening](https://github.com/epinio/epinio/blob/bfff304e42d46cf1fb1fb576c7288f88d65e194a/internal/api/v1/application/create.go#L144) to avoid conflicts with existing ingresses and the whole logic would become even more complicated, while the end result would also be less consistent. What do you think about my suggestion with the subdomain above @riqueps ?

**Comment by riqueps** [comment]
@jimmykarily I just realized that my old installation was at 1.0.0.

That would be great!!

**Comment by gitricko** [comment]
> This change was introduced in `1.1.0`. Are you sure the other installation are on that version? You need to push a new app for this to happen, old apps won't get updated (e.g. apps deployed when still on `1.0.0`).
> 
> The default application chart changed here: [epinio/helm-charts@cbb88ca](https://github.com/epinio/helm-charts/commit/cbb88ca) for version `1.1.0`.
> 
> You can always set the routes manually with the `--route` flag of `epinio push`. We could maybe add the suffix only when there is a conflict but [there is more validation happening](https://github.com/epinio/epinio/blob/bfff304e42d46cf1fb1fb576c7288f88d65e194a/internal/api/v1/application/create.go#L144) to avoid conflicts with existing ingresses and the whole logic would become even more complicated, while the end result would also be less consistent. What do you think about my suggestion with the subdomain above @riqueps ?

So it is a feature NOT a bug ;-). Kidding aside, we found this issue surprising as we have a use case that we need to control our URI. eg:
- ui app: uiapp.system.domain
- ui-backend: uiapp-api.system.domain

Because it is easy to use epinio CLI, we using to for our deployment... with this "feature" our app broke because the new URI becomes

- uiapp-a279f.system.domain
- uiapp-api-a279f.system.domain

I think `--route` will work for us as it is just a simple change in our deployment script. But i wonder if there is a simpler way to alert the developer/operator. We have this issue also in CloudFoundry. Why dont we stop the push if we know there is a conflict in the URL. I feel like we are designing for what is a rare occurrence with a slight more complicated solution (which is a postfix in the URI)

Just my 2cents

**Comment by gitricko** [comment]
I am currently modifying my automation script.. very easy fix. 

By accident, i try to push an app with --route defined and an existing app already holding the URI and this is the error that i got

```
🚢  About to push an application with the given setup
Manifest: <<Defaults>>
Name: mani
Source Origin: /Use...ai-ui/build
AppChart: 
Target Namespace: workspace
Environment 'BP_WEB_SERVER': nginx
Environment 'BP_WEB_SERVER_ENABLE_PUSH_STATE': true
Environment 'BP_WEB_SERVER_FORCE_HTTPS': true
Environment 'BP_WEB_SERVER_ROOT': .
Routes: 
1: mani.orbitnao.beta.com

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)


Create the application resource ...

❌  error pushing app to server: Bad Request: route 'mani.orbitnao.beta.com' already exists
```

If so, it seems like it is already working as the way i was suggesting... Then why would need the fix for a random string behind the app again ? Cos nobody try to "hijack" the default epinio API url because it should fail like above (unless `epinio` is NOT an epinio by definition?)

**Comment by gitricko** [comment]
> Maybe we can do something like: `appname.namespace.systemdomain` (separated with dots). With system domain being a wildcard one, this could work.

This will not work properly unless you do special magic to request cert from letsencrypt for another wildcard domain for `*.namespace.systemdomain`. Knowing user/operator can create alot of namespace... this can be problematic. Need special magic to get certmanager to request cert. 

Not sure if you want to do this...

**Comment by andreas-kupries** [comment]
> If so, it seems like it is already working as the way i was suggesting... Then why would need the fix for a random string behind the app again ? Cos nobody try to "hijack" the default epinio API url because it should fail like above (unless epinio is NOT an epinio by definition?)

History. The check to make it work like you are suggesting is something which was very recently added. The random string suffix was likely added much earlier.

... Searching ... Huh. I have to correct myself here. The PR https://github.com/epinio/epinio/pull/1640 added both the check and the suffix.

**Comment by andreas-kupries** [comment]
And re-reading comments and review comments I see https://github.com/epinio/epinio/pull/1640#discussion_r919774755 where I commented on the suffix, although only regarding the technical side of the change. I apparently did not question the need.

**Comment by gitricko** [comment]
> And re-reading comments and review comments I see [#1640 (comment)](https://github.com/epinio/epinio/pull/1640#discussion_r919774755) where I commented on the suffix, although only regarding the technical side of the change. I apparently did not question the need.

Hi @andreas-kupries, not sure what is the resolution here ? I would advocate to remove the need to add a random string post-fix unless it is an deliberate action eg: `--random-route` (actually, similar to CF)

One of major reason is that most of us will use cli for automation... if the route is taken... then error out with appropriate  message is actually good.

Just my thoughts

**Comment by jimmykarily** [comment]
> > Maybe we can do something like: `appname.namespace.systemdomain` (separated with dots). With system domain being a wildcard one, this could work.
> 
> This will not work properly unless you do special magic to request cert from letsencrypt for another wildcard domain for `*.namespace.systemdomain`. Knowing user/operator can create alot of namespace... this can be problematic. Need special magic to get certmanager to request cert.
> 
> Not sure if you want to do this...

This is already the case. For every application, if a matching certificate doesn't already exist, Epinio will try to create a new certificate with the configured issuer. It's only the route that will be different.

**Comment by andreas-kupries** [comment]
PR #1710 undos the hash postfix of the default route.
