### ISSUE TITLE
Epinio upgrade discrepancy

### ISSUE THREAD

**Issue by pedro-brito-ilia** [epinio/epinio#1702]
**Describe the bug**
After upgrading Epinio from 1.0.0 to 1.1.0 multiple times, I found some bugs on version info accross the application

- Epinio UI shows me Epinio is on 1.0.0
- `epinio version` shows me Epinio is on 1.0.0
- Epinio server pod logs show me Epinio is on 1.1.0
- 1.1.0 features are enabled, so my deployment was effectively upgraded
- `epinio info` returns the following:
✔️  Epinio Environment
Platform: generic
Epinio Server Version: v1.1.0
Epinio Client Version: v1.0.0

**To Reproduce**

1. Have a 1.0.0 Epinio deployment
2. Upgrade using `helm upgrade --reuse-values epinio epinio/epinio -n epinio --version 1.1.0`

Am I missing something? Everything appears to work fine except for the info

**Comment by andreas-kupries** [comment]
> Epinio UI shows me Epinio is on 1.0.0

Is the UI caching this information ? @richard-cox 

> `epinio version` shows me Epinio is on 1.0.0

That is the client. See also `epinio info`. Note that upgrading the helm chart updates only the server part. The client binary is unchanged.

**Comment by pedro-brito-ilia** [comment]
@andreas-kupries how do I fully upgrade Epinio? couldn't find any docs on it

**Comment by andreas-kupries** [comment]
We have docs describing how to install the epinio cli, at https://docs.epinio.io/installation/install_epinio_cli#from-the-binary-releases ... You likely used that information to get your initial cli binary, right ?

Searching https://docs.epinio.io/ I see no page about upgrading in general.

The `helm upgrade --reuse-values ...` command, wherever it was found, is the way for upgrading the server.

The UI might be because of the `--reuse-values` causing new data from the https://github.com/epinio/helm-charts/blob/main/chart/epinio/values.yaml#L87 not being applied. There are tickets to change the UI to dynamically query the server it is attached to.

**Comment by andreas-kupries** [comment]
Doc ticket: https://github.com/epinio/docs/issues/168

**Comment by andreas-kupries** [comment]
@pedro-brito-ilia Do you believe there is more to be done ? If not, may I close it ?

**Comment by pedro-brito-ilia** [comment]
@andreas-kupries I think your response + the tickets you tagged should be enough, thank you! you may close it.

**Comment by andreas-kupries** [comment]
Thanks.
