### ISSUE TITLE
extensions/v1beta1 Ingress is deprecated

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#172]
When pushing or listing apps w/ e.g. kubernetes-v1.20.4, carrier output includes warnings for

`W0225 11:53:19.188157   11295 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

So if we don't intend to support kubernetes older than v1.14, it seems we could go for `networking.k8s.io/v1` already.
I only see `c.Kubectl.ExtensionsV1beta1().Ingresses(<name>)` in "deployments/tekton.go" and "kubernetes/cluster.go".

**Comment by kkaempf** [comment]
We should not support old kubernetes versions, esp. not those unsupported by upstream.

**Comment by kkaempf** [comment]
See https://github.com/SUSE/carrier/commit/7721d610fdf27a79be980af522783671d3ffc198 for a fix, but it breaks on GKE (k8s 1.18)

**Comment by jimmykarily** [comment]
## Acceptance Criteria

- When on any k8s version >= 1.17 Carrier doesn't show any warning about Ingress version deprecation (and obviously everything works fine).

**Comment by kkaempf** [comment]
Not sure what to make of this inconsistency

https://github.com/SUSE/carrier/blob/main/kubernetes/cluster.go#L492
(using NetworkingV1)

vs.

https://github.com/SUSE/carrier/blob/main/kubernetes/cluster.go#L514
(using ExtensionsV1beta1, triggering the warning)

More surprisingly, Carrier has no (apparent) problems with `minikube start --kubernetes-version=v1.17.17` (only tested `install` and `uninstall`)

**Comment by kkaempf** [comment]
According to [Deprecated APIs Removed In 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16)

> Ingress in the extensions/v1beta1 API version will no longer be served
>
> *   Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version.

Why do we care for `extensions/v1beta1` at all ?

**Comment by jimmykarily** [comment]
I remember there was something weird happening when we tried to switch to NetwrokingV1. The first try was here:

https://github.com/SUSE/carrier/commit/7280e053af32cd53597aff80ca4c6a0046bc02ff

which was then reverted because it wasn't working on clusters <1.18+. Based on the upstream deprecation notice, it should be available since 1.14 but for some reason that didn't work.

So we reverted the above commit and added this on top:

https://github.com/SUSE/carrier/commit/ef50137adb6e46db2e8ac372c81b22b285be8bd4

the other instance which is still using NetworkingV1 was probably missed in the above commit? And if so, how does it work? We are obviously missing something here.

We should probably try to use NetworkingV1 everywhere again and try to understand why it doesn't work (if it doesn't), since it should be working since 1.14.

**Comment by kkaempf** [comment]
Thanks for the details.

This one
> 
> [7280e05](https://github.com/SUSE/carrier/commit/7280e053af32cd53597aff80ca4c6a0046bc02ff)
> 
doesn't work as-is, since you cannot use `Name` and `Number` in `networkingv1.ServiceBackendPort`

> which was then reverted because it wasn't working on clusters <1.18+.

Looking at the [Detailed Release History for Active Branches](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#detailed-release-history-for-active-branches) we see that
- 1.17 is EOL since mid-January 2021
- 1.18 will be EOLed (Apr 30th 2021) before our open source release
- 1.19 EOL is end of September 2021

1.17 is also the oldest release available in minikube today.

I wouldn't expect any 'production use' of Carrier within 6 months of the open source release. In this light, I would abandon 1.17 asap and 1.18 soon.

> We should probably try to use NetworkingV1 everywhere again and try to understand why it doesn't work (if it doesn't),

Agreed. I will continue testing with 1.18 or later now.

**Comment by jimmykarily** [comment]
> doesn't work as-is, since you cannot use `Name` and `Number` in `networkingv1.ServiceBackendPort`

https://pkg.go.dev/k8s.io/api/networking/v1#ServiceBackendPort :thinking:

**Comment by kkaempf** [comment]
:laughing:
I tried it, believe me :pleading_face:

**Comment by jimmykarily** [comment]
networking/v1 doesn't work in clusters < 1.18 (but networking/v1beta1 does work)
extensions/v1beta1 is removed on 1.22 and works with older clusters too. Since both `extensions/v1beta1` and `networking/v1beta1` are removed in 1.22 but the `extensions` one works with more versions there is no benefit from switching to `networking/v1beta1`. We decided to switch to `networking/v1` as soon as 1.22 is out. Then we no longer support clusters <1.18.

The warnings have been hidden here: #354  . Closing this.
