### ISSUE TITLE
Export push directly to OCI registry

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1770]
**Is your feature request related to a problem? Please describe.**
I would like to push my application as a set of OCI artifacts so that Fleet can pick it up and run/upgrade the application in many downstream clusters.

**Describe the solution you'd like**
I would like an additional subcommand that will pack up a built and deployed application and push it.

`epinio export <app-name> --container <container-OCI-tag> --chart <chart-OCI-tag>` 

This would require auth which could be difficult so it should likely pull down locally then push using the client's auth. It would make sense to just be a second step after https://github.com/epinio/epinio/issues/1352 

**Additional context**
What might be a bit tricky is that the two are obviously linked so the requested container tag might need to be rendered into the chart's values as well.

**Comment by enrichman** [comment]
Ref: https://github.com/epinio/epinio/issues/1157

**Comment by ksondere** [comment]
Pretty please?

**Comment by andreas-kupries** [comment]
Not on our radar at the moment. Please re-open if important to an actual usecase

**Comment by agracey** [comment]
This is an important use-case since it allows for integrations with other CD systems in a clean way.

**Comment by abonillabeeche** [comment]
Please implement. This is currently requested by one of our customers.

**Comment by andreas-kupries** [comment]
@agracey Your initial description mentions container and chart as elements to be exported, with a chosen tag.
What about the `values.yaml` ? That file links the container to the chart by configuring the chart appropriately.

Although the container information in the file will be for the registry used by the E installation.
I.e. if we want this to be directly usable the exporter will have to rewrite that part of the file.

Can OCI registries handle plain files ?
Can helm pull not just the chart from the OCI registry, but a referenced values.yaml as well ?

Note: It should already be possible to configure an OCI registry as the external registry used by E to save/pull container images from. That part of the system already has the ability for auth __(*)__. In that situation only chart and `values.yaml` would have to pushed/exported too. And the `values.yaml` would contain the proper container/image reference by design.

And being reminded of that part it becomes clear a push to any other OCI registry can be done server side.
The client simply has to provide all the necessary credentials for auth.
And it can get these through command flags.

Hm. Or not, maybe ... The server does not do direct registry access. Access is from the staging pod to save the generated image, and then from the app pod to pull. ... ... ... Remembered, regular export uses a skopeo job to pull the image into the local PV to then copy it further ... Should be possible to launch a skopeo job for pushing the image, etc. into the desired registry. 

---
Ad __(*)__:
```
global:
  # Skip if containerregistry.enabled is true
  registryURL: ""
  registryUsername: "admin"
  registryPassword: "changeme"
  # Used in registry path when pushing -> "external.tld/apps/APPNAME"
  registryNamespace: "apps"
```

**Comment by andreas-kupries** [comment]
@agracey The initial spec makes no mention of how to specify the desired destination registry ?!

This also connects to the following ...

Having looked deeper into the how E handles an external registry I found that beyond user/pass E also needs/uses
```
containerregistry:
  # The certificateSecret is used to load the certificate of the registry in the staging job.
  # The certificate has to be in PEM format within in a 'tls.crt' key (it can be an Opaque secret).
  # It also has to be trusted by the kubelet, and it needs to be added in the cluster as well.
  certificateSecret: ""
```

i.e. certs to be used for the secure connection.
Note the __has to be trusted by the kubelet, and it needs to be added in the cluster as well.__ part.

At this point I suspect that we will need some kind of setup outside of E for any desired destination registry, at least for the certs. If so then having some more external setup, i.e. k secret for the other configuration data, i.e. url, user, pass, ... should be no big problem either. At that point E would only have to search/find these secrets, and offer these to the user for selection (__by name__).

See also #2488 for something similar done for setting up auth data to access private git repos. Not as complex as here I suspect, due to not needing certs or if needed, not needed to be installed into the cluster.

Still some similarity to what I am thinking about here.

**Comment by andreas-kupries** [comment]
Ok, confirmed yesterday's research into the existing handling of an external registry by E staging and wrote it up more coherently.

[E-ext-registry.md](https://github.com/epinio/epinio/files/12290640/E-ext-registry.md)

Based on that information an initial draft spec was written.

[OCI-export.md](https://github.com/epinio/epinio/files/12290648/OCI-export.md)

@agracey Please have a look and comment.

**Comment by andreas-kupries** [comment]
@agracey 

Looking at the example command from your description, i.e.
```
epinio export <app-name> --container <container-OCI-tag> --chart <chart-OCI-tag>
```

I notice that it does not mention `values.yaml` for the upload, just chart and container.

Point here is that the E application consists of three pieces, namely:
- the container image with the runtime
- the common app chart, a configurable helm chart, and
- a values.yaml which links the two

and for the PR I was working on uploading all three pieces.
However for Fleet to handle this I guess now that you truly want only chart and image, and that deploying the chart should be all that is needed to run the app. No values.yaml to configure.

Can you confirm ?

---
For background, coming back to the spike after 3 weeks I implemented chart push today and noted that I cannot set name and tag of the chart in the push command. I have to unpack the tarball I have, edit the `Chart.yaml` to set the desired values, and then repack the tarball. And at that point it should be a trivial step to the integrate information from the app's `values.yaml` into the chart's `values.yaml` and not upload the app `values.yaml` as a third piece.

And looking again here this may have been your intent all along.

Thus my question above.
