### ISSUE TITLE
Fix Nginx CVEs

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#1783]
The [Artifact Hub security report](https://artifacthub.io/packages/helm/epinio/epinio?modal=security-report) and other tools reported some CVEs from the Nginx image that we are using.

We should try to remove the dependency, or choose a different/hardened Nginx image (SLE BCI?)

**Comment by andreas-kupries** [comment]
Looking at the report for the bitnami nginx chart, using nginx 1.23.1:

https://artifacthub.io/packages/helm/bitnami/nginx?modal=security-report

Type | critical | high | medium | low | unknown | Total
-- | -- | -- | -- | -- | -- | --
Fixable | 0 | 1 | 3 | 0 | 1 | 5
All | 1 | 8 | 5 | 64 | 1 | 79

Versus nginx 1.23.0 we use:

Type | critical | high | medium | low | unknown | Total
-- | -- | -- | -- | -- | -- | --
Fixable | 8 | 16 | 12 | 6 | 0 | 42
All | 9 | 29 | 27 | 99 | 0 | 164

The numbers go down significantly. The .1 is still marked as `F` however. Likely because the critical/high issues left.

**Comment by mmartin24** [comment]
Checked improvement when comparison vulnerabilities in artifacthub.io for epinio versions `v1.3.0` vs `v1.4.0`

Epinio version | critical | high | medium | low | unknown | Total
-- | -- | -- | -- | -- | -- | --
v1.3.0 | 12 | 50 | 77 | 129 | 11 | 279
v1.4.0| 5 | 35 | 53 | 121 | 7 | 221

![image](https://user-images.githubusercontent.com/37271841/197750230-7f2f7298-f3dd-48ce-8a98-7127af053754.png)
