### ISSUE TITLE
Service mount points should be predictable 

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1808]
**Describe the bug**

If I create an instance of a service from the catalog, I don't know what the name and mount point will be so I can specify that in my code.

For example, if I create a `postgres-dev` service called `postgrestest`, the secret is mounted at `/configurations/x552e4168057e6c22af136063fa72-postgresql`. 

**Expected behavior**
I would expect that the mount point for reading configuration would be predictable. This would likely be the name of the service instance (`/configurations/postgrestest` in the example above

**Comment by gitricko** [comment]
+1 to this... currently, we are using epinio cli to retrieve the values again.. like how this is for the wordpress

https://github.com/epinio/example-wordpress/blob/main/README.md#step-7---push-the-application

which is works but why... unless the reason is to avoid name collision for service instance

**Comment by andreas-kupries** [comment]
The mountpoints are created from go code, i.e. the API server ... The names are derived / the same as the configuration name.
For configurations derived from a service we know the service they are coming from (origin field in the model). We should be able to use this to make a user-readable name for the mountpoint ... Only issue will be when a service generates multiple configurations. These will require some kind of disambiguation ... Maybe a serial number ?

**Comment by andreas-kupries** [comment]
I was mistaken. The go code simply passes the names of the configurations into the app chart, as `[]string`, and the chart then uses these for the volumes (names, and name of config secret), and volume mounts (vol name, and path).

To separate the paths from the config names the slice has to be changed from `[]string` to `[]struct { config: string, path: string }`.

Compatibility thoughts:

  - Old server ... comes from an old helm chart, referencing the old app chart ... is not expected to deal with applications based on the new chart.
  - New server ... new helm chart, will reference the new app chart ... And may have to deal with apps using the old app chart ... This is actually very similar to having to deal with application deployed with a custom chart. The active workload knows the chart it was deployed with ...
    The difference. We have a change in the api chart API to deal with here. On changes the new server would use the old chart and provide the new information regarding configurations, something the old chart does not understand. This however gives us the solution as well. Provide old __and__ new information. I.e. make the change an extension of the API ... And remove the old information a few releases later, giving users a proper transition period.
    This is like we have for services still based on helm controllers. The current binary is still able to operate on HC-based services, while it does not create them anymore. In a few releases that support will go away.
    Actually, we can make the extension without ever foregoing the old information.

So, instead of changing `configurations` from `[]string` to the new type, keep that, and provide an additional field ... `configpaths`, also of type `[]string`. This runs parallel to `configurations`. The old app chart will ignore this information. The new chart will use it as source of path names for the bounds configurations.

Except, this is not viable as is ... The templating cannot range over both slices concurrently ... We either have to make it a slice of a struct as noted at the top, or an object keyed by configuration name to map to the associated path name.

**Comment by andreas-kupries** [comment]
Spec:

  - Keep existing field `configurations` of type `[]string`, for compatibility.
  - Add new field `configpaths` of type `[]struct { name : string, path : string }`.

Old standard app chart uses the old field. Updated standard app chart uses the new field.
