### ISSUE TITLE
Bug: Able to create services with the same name if one is from 1.3.0 (helm controller based), and the other is from 1.4.0 (without HC)

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio#1849]
Context.

I created in `v.1.3.0` a custom service named mycustom-service and bound to an app testapp . The hash for this version is `x5dc8835923fe6cac2053d8aa18b1-mysql`
I upgrade to `v.1.4.0` and create the same service with hash for `v.1.4.0`: `x8e5ee833a0f2faebaf5c4171baca-mysql `
When I try to bump a second app, `testapp2` it is bound to both services:

```
🚢  Listing configurations
Namespace: workspace

✔️  Epinio Configurations:
|                NAME                 |            CREATED            |  TYPE   |      ORIGIN      |   APPLICATIONS    |
|-------------------------------------|-------------------------------|---------|------------------|-------------------|
| x5dc8835923fe6cac2053d8aa18b1-mysql | 2022-11-10 09:03:51 +0100 CET | service | mycustom-service | testapp, testapp2 |
| x8e5ee833a0f2faebaf5c4171baca-mysql | 2022-11-10 10:04:21 +0100 CET | service | mycustom-service | testapp2          |
➜  epinio git:(main) epinio service list                          

🚢  Listing Services...
Namespace: workspace

✔️  Details:
|       NAME       |            CREATED            | CATALOG SERVICE | VERSION |  STATUS  |   APPLICATIONS    |
|------------------|-------------------------------|-----------------|---------|----------|-------------------|
| mycustom-service | 2022-11-10 10:04:19 +0100 CET | mysql-dev       | 8.0.29  | deployed | testapp, testapp2 |
| mycustom-service | 2022-11-10 09:03:46 +0100 CET | mysql-dev       | 8.0.29  | deployed | testapp, testapp2 |
```

**Comment by andreas-kupries** [comment]
Thanks. Confirmed, without having to bind the services to applications.
Just creating them with 1.3.0 and 1.4.0 is enough.

The 1.3.0 service consists of an helm chart spec in the epinio namespace, and a helm release in the target space.
Trying to create two services of the same name fail on the duplicate helm chart spec
The 1.4.0 service consists of a secret in the target namespace, and a helm release in the same. With a different derivation of the name.
Trying to create two services of the same name fail on the duplicate secret.
Doing a two services with 1.3.0, and 1.4.0 they pass each other on the first (spec vs secret) and the helm release have different names due to the different derivations, so no clash there either.

The 1.4.0 validation of services has to be changed to properly recognize 1.3.0 services as well.
And better do it explicitly instead of having a creation op fail on the lower-level resource (helm chart spec, secret).
