### ISSUE TITLE
namespaces still exists immediately after `carrier uninstall`

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#186]
After an incomplete install[1], I did `carrier uninstall` which finished successfully, and a `carrier install` following immediately.

This resulted in
```
🚢 Carrier installing...

Configuration...
  🧭  system_domain: 
error installing Carrier: Namespace traefik present already
```

A `kubectl get namespace` did _not_ show `traefik` and a subsequent `carrier install` re-starts the installation.

It seems as if `carrier uninstall` returns too early, while the namespace deletion isn't completed yet.

---
¹ I tried `carrier install` on minikube and it failed with `error installing Carrier: Timed out waiting for LoadBalancer IP on traefik service.` - but that's a different problem ;-)

**Comment by kkaempf** [comment]
This is true for all namespaces

**Comment by kkaempf** [comment]
> This is true for all namespaces

No, it's not.  Carrier does

> 🕞   Waiting for workloads namespace to be gone ......

for workloads, but no other namespaces

**Comment by jimmykarily** [comment]
The reason we waited for `workloads` is because there are some race conditions that prevent it from being deleted if some other components are removed first. iirc it was some finalizers that were left there. So we remove it first and after it's done we remove the rest of the components. It part the domain knowledge Carrier has that makes it useful in the first place.

**Comment by jimmykarily** [comment]
There have been a lot of changes on how `uninstall` works the last months. This issue is about a rather old version. Please re-open is you encounter issues with the latest version. Closing.
