### ISSUE TITLE
Check for external load balancer before installation

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#187]
`carrier install` fails on minikube without metallb (as described [here](https://github.com/SUSE/carrier/blob/main/docs/install.md))

Carrier should add a check for metallb (on minikube) to warn users (resp. just install metallb)

**Comment by kkaempf** [comment]
While `install_client.go` has [a useful error message](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/internal/cli/clients/install_client.go#L357), it is not shown in all cases.

With `minikube` 1.21.0 and k8s 1.20.7, I was just getting
```error installing Epinio: failed waiting for Traefik Ingress to have get a Load Balancer: timed out waiting for the condition```
after (again) forgetting to enable MetalLB.

**Comment by kkaempf** [comment]
It takes **several minutes** until a user sees the Traefik timeout. Can Epinio fail faster ?

We should try to improve the initial user experience here, like
* checking early if the 'install environment' is complete and warn if important pieces (like load balancer) are missing
* detect the k8s implementation and print hints (like "you're running minikube, hope MetalLb is installed, trying anyways ...") at the beginning of `epinio install`
* fail faster
* ...

**Comment by manno** [comment]
You are seeing that message, because Epinio 0.0.18 added [another wait loop for the loadbalancer IP](https://github.com/epinio/epinio/commit/cafa28c070099f26f06e156e5643cfd3b858c6d1) to the traefik part of installation. However, there is an older check with a better error message being done later in the installer. I think both checks are necessary (because of --skip-traefik) and should use similar code and error messages.

Fixing the error message to point to the docs and using the same check in both places is an easy cleanup.

However, you are suggesting that Epinio detects the platform it's installed on and then runs a number of pre-checks, i.e. check if minikube was installed with the metallb addon. MetalLB is a network or [external loadbalancer](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/). Epinio is limited to things that are in the cluster. We can deduce the presence of metallb, though.

* does the node have a `minikube.k8s.io/version` label
* does the cluster have a `metallb-system` namespace

I'm not sure where that belongs, I don't think we test for any of the other platforms.

**Comment by kkaempf** [comment]
My main concern is the initial first-time-user experience. Currently it takes way too long until an [unhelpful error message](https://github.com/epinio/epinio/issues/187#issuecomment-876236496) is displayed.

**Comment by manno** [comment]
Ok then. For planning I'd suggest we just do the bug fix for the error message/code duplication.

While we can optimize the wait time for some cases, like yours (installing minikube without metallb), it's not possible in general. Some providers take minutes before they assign a IP. Also, if the failure is on the side of the cloud provider (account setup/balance,..) we can't do anything but wait for the external loadbalancer to fail.

**Comment by kkaempf** [comment]
> While `install_client.go` has [a useful error message](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/internal/cli/clients/install_client.go#L357), it is not shown in all cases.
> 

This error message is never reached.

`install_client.go` checks for `Timed out after` [in the error message](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/internal/cli/clients/install_client.go#L358) which is generated in [`ExecToSuccessWithTimeout`](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/helpers/exec.go#L122)

But `traefik.go` calls [`WaitUntilServiceHasLoadBalancer`](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/deployments/traefik.go#L137), calling [`WaitUntilServiceHasLoadBalancer`](https://github.com/epinio/epinio/blob/0a8dd213d2113428b71f595cc28f281319492c75/helpers/kubernetes/cluster.go#L422).

The `Timed out after` error message is never generated in the Traefik setup workflow.
