### ISSUE TITLE
[Epic] Map users to roles

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#1946]
We need a generic way to define mappings between JWT claims and what actions are allowed.

This system must:

- Be easy to understand and administer
- Provide least privileges
- Allow separate roles for listing, reading details, editing, and creating
- Allow soft multi-tenancy across namespaces (e.g. user A has read write access for apps on one namespace but read only on another namespace)
- Not require too many changes to the existing code base

My initial thought is that a secret per namespace containing the whitelist ACL could provide this without too much administrative overhead. 

The ACL data in the secret could look something like this 

```
application:
  jwt_claim_name: rwlcd
  jwt_claim2: l
service:
  jwt_claim_name: rw
  jwt_claim2: rld
```

Where the RHS of the claim mapping is a string with a combination of letters:
- r -- read 
- w -- write/edit
- l -- list
- c -- create
- d -- delete
- a -- all

 \* A user with multiple claims would get access to the union of access and an admin would have access to everything. 

Additionally, as long as the secret/configmap is mounted in the pod without any subpath, changing it would not require a restart of the API. 

Another option is to build role bindings as their own CRDs. My concern here is that this would mean several additional requests to the kubeapi for every request reducing the scalability of the platform.

**Comment by enrichman** [comment]
The JWT is issued by Dex, and I don't think we have much flexibility there (i.e. can you add claims?) . Anyway this is not really an issue, the token is used only for the authentication. We validate the JWT, load the Epinio user with its role, and then we check that he's allowed to perform the actions. So the authorization part is done later in the chain.

I'm not sure how the multi-tenancy would work with a secret per namespace, since they can be created dynamically. From a least privilege perspective if there is no secret then you should not be able to do anything, so a new namespace will be accessible only after that an operator will assign some roles/permissions to it.

Before digging too much into the details I would like to understand better the requirements.

From your example I can assume that the "jwt claim" is an "epinio role". I would change the structure to something more "kube-friendly":

```yaml
roles:
- id: auditor
  rules:
  - resources: [ "application", "services" ]
  - verbs: [ "get", "list" ]
- id: dev
  rules:
  - resources: [ "application", "services" ]
  - verbs: [ "get", "list", "create" ]
```

These roles could be defined globally, in the Epinio namespace, in a configmap for example. I'm still not sure on how to map these to a specific namespace/user.

---

To add some context when I initially tried to setup the authentication I played a bit with [Casbin](https://casbin.org/), and I found it pretty nice. The needed [changes](https://github.com/epinio/epinio/pull/1404/files#diff-af814de535e41c608b044a7a1c65ee3198beda66f7bb8398daf7cff7cbdd7c3d) on the server where really a few, because all the work is done on the [configuration](https://github.com/epinio/helm-charts/pull/185) side.

I think that we can think about using it somehow.

If we think that writing a Casbin configuration is too much work maybe we can translate the Epinio ACL to the corresponding Casbin configuration. But maybe is not even needed, and we could use directly the ACL.

**Comment by enrichman** [comment]
I had a thought about this, and I'm writing down some key parts just to get some feedback. I would like to play with this solution btw. It should be feasible without not many changes in the actual codebase.

Some concepts.

## Role

A Epinio Role can perform a set of Actions.  
A role can be assigned to multiple users, and for each user it can be scoped to a namespace.

I.e. the "dev-read" role can be assigned to user Alice as a default role, and it can be assigned to user Bob just for the namespace "foo".

## Action

An Epinio action is an operation that can be done on Epinio. It's an "high level" concept and it's something that can be done via one or many APIs. Usually every action is scoped to an Epinio CLI command, since the CLI is mostly feature complete.

For example the Epinio `info` command is mapped with the `GET /info` endpoint, but the Epinio `push` command perform multiple requests, and it needs access to the `create`, `update`, `import-git` APIs.

If an action is granted to a role, then also all the subset actions should be granted as well. If a role has the `push` action, then also the `update` can be performed.

On the frontend I will expect this kind of visualization:

- [ ] app
  - [ ] push
  - [ ] create
  - [ ] env
    - [ ] set
    - [ ] get
-  [ ] service
   -  [ ] create
   -  [ ] delete

## Some implementation ideas

The action tree could be obtained from an `/roles/actions/config` endpoint that returns a list of available `Action`s.

```json
[
    {
        "id": "app_push",
        "name": "App push",
        "description": "App push can push an app",
        "depends_on": [
            "app_create",
            "app_import-git"
        ]
    }
]
```

The `depends_on` field can be used to check which are the actions that needs others action granted in order to be performed.

An action could also have multiple actions (note: the `depends_on` could not be needed for the inner actions because it's implicit):

```json
{
    "id": "app",
    "name": "App",
    "description": "Can perform action over app",
    "actions": [
        {
            "id": "app_push",
            "name": "App push",
            "description": "App push can push an app",
            "depends_on": [
                "app_create",
                "app_import-git"
            ]
        }
    ]
}
```

Some more fields could be added for the frontend, in order to have other informations (such as the type of the action, if needed (read, write, delete or rw, or anything).

The actions are "generic" and not mapped to the APIs in order to be open to further modification, while keeping the functionality. But on the server side we will need to have this mapping somewhere in order to check if the role that called the endpoint have the grants for the API.
I.e.: when someone calls the `update` endpoint we need to check if the role has one of the action with the update endpoint available.

### Roles

Roles can be just Kubernetes secrets with the list of granted actions.

### User

An annotation will be used to store the roles of a user, eventually scoped in the namespace with the `::` separator:

```yaml
annotations:
  epinio.io/roles: "[\"auditor\", \"admin::foobar\"]"
```

When the user will request a resource in a specific namespace then we will check for any role for the specific namespace (eventually merging the available actions). If no specific namespaced-role is present then the "global" roles will be used.

This means that a namespaced-role can be used to either extend or restrict actions of a user in a specific namespace. I.e. the `admin` role can be restricted to a `dev` role in the `workspace` namespace adding to the user the `dev::workspace` role. On the other hand a user with a global `dev` role can be an `admin` in just some namespace (`admin::workspace`).

There are still few things to clarify. Some actions are not namespaced (maybe we should add this field in the Action type), and so they will need to be scoped to a global role. Also we need to be careful on defining the right permissions/actions to avoid some privilege escalations (for example if providing in the future a `role_create` action).

An example of a global action is the namespace creation. It cannot be scoped to a single namespace.  

Using a `namespace_creator` role with just the `namespace_create` action a user will be able to create a namespace. But if this role is going to be assigned to a single namespace `namespace_creator::foobar` then it will be useless.  
Maybe in this particular case we could let the user perform the namespace actions in the specified namespace (such as creating or deleting the namespace, for development purposes).

I'm not sure we could keep the exact same behaviour that we have at the moment, but it's probably not a big deal.

### Casbin

I was thinking to use Casbin to create the policy to be granted (there is still a branch with a previous spike for this), but it's probably not even needed. The actions configuration can be hardcoded, and so the check could be performed easily without adding the extra dependency.

**Comment by richard-cox** [comment]
Would the management of actions, roles and users be done solely outside of epinio (cli / ui)? If not we need to also think about the APIs to support this. 

- assigning roles - listing users and roles, updating user
- reviewing role definitions - listing actions
- creating/updating roles - listing roles, updating role

etc

This is a bit of scope creep, but we should bare in mind enterprise users will probably want to assign roles to groups (avoiding manually applying roles to 100s of users)

**Comment by gitricko** [comment]
Would love to give you feedback on the requirements, if you reach out. We have implement integration with AWS ID Center and now going for GCP

**Comment by fabioch** [comment]
It would be important for us, and generally for large organizations, to be able to manage centrally role mappings. 

A typical scenario consists of a central IdP, for example Azure AD, where users are defined and processes are in place to enforce corporate requirements, such as periodic user access certification, break-glass access to production systems, and approval workflows. Assigning role mapping to users directly inside the applications violate our security policies and it would be difficult to manage at scale.

Considering the very welcome extensions that you are designing, it would be great if we add the possibility of using the claims to create role attribute mappings. I.e. groups in Azure AD will be mapped to roles in Epinio.

An alternative approach would be to use SCIM, but it requires more work for each customer for the implementation. I would avoid custom user role mappings done using API because it is not a standard solution, it requires custom development and will most likely not be allowed. SCIM does that.

**Comment by enrichman** [comment]
Maybe I wasn't clear but the actions are bound to roles, and these roles are applied to different users. And in the same way we have now we will map external groups to internal Epinio roles.

@richard-cox yep, obviously this will need a set of APIs to CRUD these roles, and manually assign these when non using external integration.

**Comment by gitricko** [comment]
I agree... we do need set of API / maybe extended to cli for setting CRUD roles when epinio is running as `stand-alone` mode. However, consider providing a function to disable this (not allowing this) when epinio is tie to/configure with central IdP

> @richard-cox yep, obviously this will need a set of APIs to CRUD these roles, and manually assign these when non using external integration.

**Comment by enrichman** [comment]
And done! We hope to release soon a `rc` for this.
