### ISSUE TITLE
epinio user (log in on from dex) cant do 'epinio app exec APP-name'

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#2003]
**Describe the bug**
It seems like users that login via dex. eg: `epinio login --oidc <epinio-url>` cant do shell to container.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install epinio version `1.5.2`
2. login using dex user: user - admin@epinio.io/password
3. push an app (we use conda-app via paketo's sample)
4. try container shell via: `epinio app exec <app-name>` . It will fail
5. Now, remove epinio session's file in your current directory
6. login without dex. epinio login  <epinio-url>
7. try  `epinio app exec <app-name>` again... It will work

**Expected behavior**
dex and local user should work the same.

**Logs**
```
╰─$ epinio app exec conda-app

🚢  Executing a shell
Namespace: workspace
Application: conda-app

❌  error getting a shell to application: error sending request: Get "https://epinio.internal.frxxdenv.xxx.com/wapi/v1/namespaces/workspace/applications/conda-app/exec?authtoken=eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlcGluaW8tc2VydmVyIiwiZXhwIjoxNjczNzk4OTc3LCJ1c2VyIjoiYWRtaW5AZXBpbmlvLmlvIn0.yd6Cdu8zRo_LpDNTgmAPhE9RtaoSo1kH0gnlJ_XsmUgAMYZqC7MZOU__ygHNidvO-WAxKUkfIv7UixTMXoc2fn2ME7CwKIB0ypkSRUVPN11XFceWQQqDD0C_6gEdXA2Agl4b0StEHMqjfySCDm-E7fFGLYvIbJNs2axJqwOiBatApv1PB-7maeImk1WUKJiXhZgEqXPRVW_amhRk1vj1DnCBC7ale1I3cs7oPGF-IO8Kv2fXm75h96Ml4JLatoRK3EmM4WT8UGSo_H538SVFRhEWw2s3jrnGVy86fvbO1f_i8UFO9dKXP-ahUSjWDtGRDANCgtBV4Am_ZvQroLh95Q": malformed HTTP response "\x00\x00\x1e\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x01\x00\x00\x10\x00\x00\x04\x00\x10\x00\x00"
```

**Cluster (please complete the following information):**
 - Provider: K3D
 - Kubernetes Version: [e.g. 1.24]

**Desktop/CLI (please complete the following information):**
 - OS: [e.g. Linux, MacOS]
 - Epinio Version: 1.5.2

**Comment by gitricko** [comment]
cc: @pedro-brito-ilia  @riqueps

**Comment by andreas-kupries** [comment]
# Sessions to confirm/falsify ...

Regarding the __`exec` into still running sample-app :heavy_check_mark:__ lines in the session logs below ... I ran the `exec`, waited to see a shell prompt and ran the commands `pwd` and `ls -l` in that shell to confirm that I am in the container. Then `exit`ed.

Let's begin

  - k3d/k3s local cluster (kube 1.25)
  - Epinio Version: v1.5.2-45-g6fa5d830
  - regular login with admin/password (automatic through dev deployment helper script)
  - `push` assets/sample-app
  - `exec` into sample-app :heavy_check_mark: 
  - re-login with oidc, same credentials
  - `exec` into still running sample-app :heavy_check_mark: 
  - __not reproduced__

Retrying, with commands in slightly different order

  - k3d/k3s local cluster (kube 1.25)
  - Epinio Version: v1.5.2-45-g6fa5d830
  - regular login with admin/password (automatic through dev deployment helper script)
  - re-login with oidc, same credentials
  - `push` assets/sample-app
  - `exec` into sample-app :heavy_check_mark: 
  - __not reproduced__

Third

  - k3d/k3s local cluster (kube 1.25)
  - Epinio Version: v1.5.2-45-g6fa5d830
  - regular login with admin/password (automatic through dev deployment helper script)
  - squash settings.yml
  - login with oidc, same credentials
  - `push` assets/sample-app
  - `exec` into sample-app :heavy_check_mark: 
  - __not reproduced__

Differences local vs submitter:
  - kube 1.25 (vs 1.24)
  - Epinio 1.5.2-45-... (vs 1.5.2)
  - App `assets/sample-app` (vs `conda-app`)
  - Still have the regular login going on, even if the resulting settings are thrown away. The server still sees it

Fourth trial

  - k3d/k3s local cluster (kube 1.25)
  - Epinio Version: v1.5.2 (moved checkout to version tag!)
  - regular login with admin/password (automatic through dev deployment helper script)
  - squash settings.yml
  - login with oidc, same credentials
  - `push` assets/sample-app
  - `exec` into sample-app :heavy_check_mark: 
  - __not reproduced__

Differences local vs submitter:

  - kube 1.25 (vs 1.24)
  - App `assets/sample-app` (vs `conda-app`)
  - Still have the regular login going on, even if the resulting settings are thrown away. The server still sees it

Pleading the fifth

  - k3d/k3s local cluster (kube 1.25)
  - Epinio Version: v1.5.2 (moved checkout to version tag!)
  - (removed the regular login from the deployment helper for this so that it does not happen)
  - login with oidc, admin/password
  - `push` assets/sample-app
  - `exec` into sample-app :heavy_check_mark: 
  - __not reproduced__

Differences local vs submitter:

  - kube 1.25 (vs 1.24)
  - App `assets/sample-app` (vs `conda-app`)

At this point I have to suspect that something is different in the submitter's setup.

**Comment by enrichman** [comment]
I needed to deploy an EKS cluster to try again the configuration for the https://github.com/epinio/epinio/issues/1973.

I tried to exec in a sample app and I was able to. So also within a cloud envinroment it seems to work. The Kubernetes version was the 1.23 in this case.

**Comment by riqueps** [comment]
I did some debugs and I was able to run `epinio app exec` by downgrading epinio cli to 1.5.1

![image](https://user-images.githubusercontent.com/47371890/213293191-d8511661-99e9-4eaa-8d76-0a6c655f908e.png)

**Comment by riqueps** [comment]
To reproduce:

#### On EKS cluster:
- Eks v1.22
- Epinio Server v1.5.2
- **Amazon Issued certificates through cert-manager**
- Epinio CLI v1.5.2
  - regular login with admin/password :heavy_check_mark:
  - dex login with admin@epinio.io/password  :heavy_multiplication_x:
- Epinio CLI v1.5.1
  - regular login with admin/password :heavy_check_mark:
  - dex login with admin@epinio.io/password  :heavy_check_mark:

#### On K3D cluster:
- K3d v1.23.8+k3s1
- Epinio Server v1.5.2
- `Amazon Issued certificates through cert-manager`
  - Epinio CLI v1.5.2
    - regular login with admin/password :heavy_check_mark:
    - dex login with admin@epinio.io/password  :heavy_multiplication_x:
  - Epinio CLI v1.5.1
    - regular login with admin/password :heavy_check_mark:
    - dex login with admin@epinio.io/password  :heavy_check_mark:
- `sslip self-signed certificates`
  - Epinio CLI v1.5.2
    - regular login with admin/password :heavy_check_mark:
    - dex login with admin@epinio.io/password  :heavy_check_mark:
  - Epinio CLI v1.5.1
    - regular login with admin/password :heavy_check_mark:
    - dex login with admin@epinio.io/password  :heavy_check_mark:

**Comment by andreas-kupries** [comment]
To summarize it seems that it is the combination of

  - dex login + amazon cert + 1.5.2 client

which is broken. Moving away from any of the these (regular login, or other cert, or 1.5.1 client) makes the issue disappear.

The server was fixed at 1.5.2 ... Unclear if using an 1.5.1 server with 1.5.2 client would be broken too.
Cluster had different versions (1.22, 1.23), and platforms (eks, k3d), so the issue is likely independent of that.

Regarding `Amazon Issued certificates through cert-manager` I am currently assuming that cert-manager was configured with a "ClusterIssuer" using an AWS backend, and the Epinio install configured to use that issuer, right ?

If so, may we have the details about the cert-manager configuration/commands for that ClusterIssuer ?
At that point local reproduction should come into reach.

**Comment by thehejik** [comment]
Could you please also check if your dex ingress manifest has the proper `Issuer` and `tls` secret assigned?

**Comment by riqueps** [comment]
@thehejik 

Yes, dex ingress has dex-tls secret assigned and it's using the proper Issuer

![image](https://user-images.githubusercontent.com/47371890/213689549-0bb54c2d-fc3a-48c3-aa60-f07f224249ee.png)

![image](https://user-images.githubusercontent.com/47371890/213689833-130e4792-9a61-4b16-849a-05a40fd4bb9b.png)

But there is a weird thing with dex-tls secret, it was issued, but there are two certificates using the same secret

![image](https://user-images.githubusercontent.com/47371890/213690051-9ca78c65-b07b-4c3e-b354-c3a38fd45772.png)

Cert-manager keeps returning these logs

![image](https://user-images.githubusercontent.com/47371890/213688789-564f2c79-89dc-4537-ad61-3340c0a03c0a.png)

**Comment by andreas-kupries** [comment]
May we see the definition of the `letsencrypt-epinio` issuer ? (Who, despite the name, apparently generates AWS certs ?)

@enrichman As the dex person, any opinion on the second question, about two certs using the `dex-tls` secret ? The cert-manager logs certainly read ominous.

**Comment by riqueps** [comment]
@andreas-kupries 

```
# Creation of cluster issuer integrated with Route53
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-epinio
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "DOMAIN.COM"
      dns01:
        route53:
          region: us-east-1
          role: arn:aws:iam::XXXXXXXXX:role/CertManager
```

**Comment by andreas-kupries** [comment]
> But there is a weird thing with dex-tls secret, it was issued, but there are two certificates using the same secret

See #2041 for another report in the area. Looking to be able to fix that at least.

Oh! now I wonder if this issue could also be triggered by the cert fight.
I.e. actually different cert data stored in the secret and switching around ...

**Comment by thehejik** [comment]
@andreas-kupries I tried with the updated `helm-chart` containing the cert fighting fix for dex `ff1e3b521660` but the problem persists.

**Comment by gitricko** [comment]
Any update on this bug ? I just tested on 1.6.2 server and epinio 1.6.2 client fails to login when epinio user used dex for login.

However, if you use client 1.5.1, it worked on 1.6.2 server... Same as reported by @riqueps 

I was wonder whether the bug is just CLI and not server side... apparently, 1.5.1 cli works with dex-users

tagging: @riqueps

**Comment by andreas-kupries** [comment]
Unfortunately no progress at the moment :(

**Comment by andreas-kupries** [comment]
Some progress today however. The issue is only in a difference of the login command between the versions. The version of the client used for the "action" (`exec`, or `port-forward`) then does not matter. Table:

|Server	  |Login  |Action |Exec		|Port-Forward	|
|---	  |---	  |---	  |---		|---		|
|1.6.2	  |1.6.2  |1.6.2  |:boom:	|:boom:		|
|1.6.2	  |1.6.2  |1.5.1  |:boom:	|:boom:		|
|1.6.2	  |1.5.1  |1.6.2  |:ok:		|:ok:		|
|1.6.2	  |1.5.1  |1.5.1  |:ok:		|:ok:		|

Comparing the `settings.yml` files produced by the two versions shows that 1.5.1 saved some certs into the settings which 1.6.2 does not. Copying these certs into the 1.6.2 settings.yaml and the commands work. The error message from `app exec` looks to be simply what you get of the websocket stuff then the TLS handshake fails for a bad/missing cert.

I am now suspecting PR #1964 in 1.5.2. It is the one change in the login area from .1 to .2 and later.

**Comment by andreas-kupries** [comment]
Yes. That PR lost (i.e. failed to save anymore) all certs which were trusted without user intervention.

**Comment by andreas-kupries** [comment]
Fix via #2077

**Comment by gitricko** [comment]
nice find @andreas-kupries

**Comment by thehejik** [comment]
Validated in v1.7.0 - used public domain, letsencrypt-production issuer and epinio commands: `login --oidc; app push; app exec`. All good.
