### ISSUE TITLE
Different Healthcheck to determine epinio app (k8 pods) is ready

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#2075]
**Is your feature request related to a problem? Please describe.**
Is there a way to configure epinio push app where by we can specify when an app is healthy by:
- http
- port
- process

very similar to CF: https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html#types

I think this will be a useful feature especially, the application might be doing some short init during boot up and if that task a few seconds, there will be timeout or down time when K8 just shutdown the previous app after the push.

**Describe the solution you'd like**
eg: epinio push --name abc-app --health-check=http
eg: epinio push --name abc-app --health-check=process
eg: epinio push --name abc-app --health-check=port:8080

**Describe alternatives you've considered**
nil

**Additional context**
This request is related to this I think:
https://github.com/epinio/epinio/issues/900

**Comment by enrichman** [comment]
Hi @gitricko, just to understand a bit more, is this something related to the liveness/readiness probes?

Epinio uses a standard Helm chart to deploy its applications, and at the moment it doesn't support them. This can be solved customizing the chart (https://docs.epinio.io/next/references/customization/appcharts) but it's probably a common need that should be addressed.

Also this issue is probably related: https://github.com/epinio/epinio/issues/1792 from @olblak 

While the port is an easy customization (it's just a value) the probes are a bit more complicated, because they could have different options (initialDelay, period, path). By the way HTTP is still the most common, and we could try to find a way to support it, maybe with parameters: 
- `--health-check "http"`
- `--health-check "http:8080/check"`
- `--health-check "http:8080/?delay=5s&period=10s"`
- `--health-check "tcp:8888"`
- `--health-check "grcp:8000"`

As @agracey mentioned this could be probably be templated with custom values, avoiding to have too many flags
- `-v/--chart-value health-check "tcp:8888"`

**Comment by gitricko** [comment]
I agree, we should default use http health check. In the meantime, any example how to do with appchart ? I think we can use a tutorial for how to leverage appchart

**Comment by enrichman** [comment]
Here should be a guide on how to do that: https://docs.epinio.io/next/howtos/create_custom_appcharts

Once that the charts are available the developer can choose the one that better fits the needs of the application.

**Comment by agracey** [comment]
For reference on the kubernetes side: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

One thing for us to keep in mind is how many options there are. I like the templated string but how much logic should we add to map the templated values to all of the different options available?

**Comment by enrichman** [comment]
I think it would be nice to cover at least some basic cases. If you need to cover more options you can still provide your own app chart.

**Comment by mmartin24** [comment]
After discussing this issue in Grooming it was decided to focus on other issues since currently exists a workaround using custom app chart.
