### ISSUE TITLE
s3 not accessible when using nginx as ingress

### ISSUE THREAD

**Issue by abonillabeeche** [epinio/epinio#2100]
**Describe the bug**
I was successfully using traefik but wanted to switch to nginx, so I reinstalled with
`--set ingress.ingressClassName=nginx`

at that point, I would fail to stage applications as they cannot be uploaded to my s3. Switching back to traefik works fine.

**To Reproduce**
1. Install Epinio 1.6.2 or 1.7.0
2. Push an app 
3. See error

```
Application exists, updating ...

Collecting the application sources ...

Uploading application code ...

❌  error pushing app to server: can't upload archive: server status code: Internal Server Error
{"errors":[{"status":500,"title":"ensuring bucket: The specified bucket does not exist.","details":"uploading the application sources blob\nServer Backtrace: The specified bucket does not exist.\nensuring bucket\ngithub.com/epinio/epinio/internal/s3manager.(*Manager).UploadStream\n\t/home/sles/actions-runner/_work/epinio/epinio/internal/s3manager/s3manager.go:213\ngithub.com/epinio/epinio/internal/api/v1/application.Controller.Upload\n\t/home/sles/actions-runner/_work/epinio/epinio/internal/api/v1/application/upload.go:86\ngithub.com/epinio/epinio/internal/api/v1.errorHandler.func1\n\t/home/sles/actions-runner/_work/epinio/epinio/internal/api/v1/router.go:52\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173\ngithub.com/alron/ginlogr.RecoveryWithLogr.func1\n\t/home/sles/go/pkg/mod/github.com/alron/ginlogr@v0.0.4/logr.go:121\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173\ngithub.com/alron/ginlogr.Ginlogr.func1\n\t/home/sles/go/pkg/mod/github.com/alron/ginlogr@v0.0.4/logr.go:34\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/recovery.go:101\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/sles/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572\nnet/http.serverHandler.ServeHTTP\n\t/home/sles/actions-runner/_work/_tool/go/1.19.5/x64/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/home/sles/actions-runner/_work/_tool/go/1.19.5/x64/src/net/http/server.go:1991\nruntime.goexit\n\t/home/sles/actions-runner/_work/_tool/go/1.19.5/x64/src/runtime/asm_amd64.s:1594"}]}
```

**Cluster (please complete the following information):**
 - Provider: rke2 1.24
 - Options: Harvester cluster with Rancher 2.7.1 and Harvester/Longhorn StorageClass
 - Kubernetes Version: 1.24

**Desktop/CLI (please complete the following information):**
 - OS: Mac Client
 - Epinio Version:  1.6.2
 - Epinio Install Options:
 ```
helm upgrade --install epinio epinio/epinio -n epinio --create-namespace --version 1.6.2 --set global.domain=dev.5glinux.com --set minio.enabled=false \
--set ingress.ingressClassName=nginx \
--set s3.endpoint=object.5glinux.com \
--set s3.useSSL=false \
--set s3.bucket=epinio \
--set s3.region=us-east-1 \
--set s3.accessKeyID=testkey \
--set s3.secretAccessKey=testkey \
--set containerregistry.enabled=false \
--set global.registryURL=jfrog.5glinux.com \
--set global.registryNamespace=epinio \
--set global.registryUsername=abonilla \
--set global.registryPassword=password
```

**Additional context**
bucket exists
DNS was configured correctly
only change was the switch between traefik and nginx

**Comment by andreas-kupries** [comment]
Had some chats with others and out of this came a possible lead to the problem.

First, as it works with traefik your s3 object store itself should be ok.

Now, when nginx is switched in I would assume that an actual nginx process would be added into the communication path between Epinio and the S3, right ?

That would be relevant because nginx usually has some kind of upload limit, a `max-body-size`. And requests with data larger than that limit get rejected. Further, AFAIR, the default limit is quite low.

For the Epinio API server's ingress we actually bump that limit up, should nginx be used for ingress, see

https://github.com/epinio/helm-charts/blob/0fb34e350de3acb5371a8f0dd00eee2937231ae5/chart/epinio/templates/ingress.yaml#L8 (It was done with commit https://github.com/epinio/helm-charts/commit/e4ba1d95402cf81d2582c6c7e6adcd88029f879d for which I do not find a PR)

That ingress however is likely not the ingress used when the epinio server talks your external S3 with nginx ingress, right ?

As such, could you look at what ingress resource in your setup controls access to your S3, and check what its nginx body limits are ? Default, or something else ? 

And a possible solution could thus be adding the same kind of thing we do for Epinio itself, i.e.

```
 nginx.ingress.kubernetes.io/proxy-body-size: 100m
```

to that ingress resource.

**Comment by andreas-kupries** [comment]
My understanding from the slack channel is that this is solved and was an issue in the homelab setup.
