### ISSUE TITLE
Cannot `--follow` staging logs

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2107]
**Describe the bug**
During the latest Deployment Sharing Session we were not able to catchup to the staging logs anymore

https://github.com/epinio/epinio/wiki/Deployment-Sharing-Session#bug-staging-logs-with---follow

We lost the connection and an `epinio app logs --staging --follow myapp` was showing only the unpack-blob.

**Comment by andreas-kupries** [comment]
Referencing https://github.com/epinio/epinio/issues/2106#issuecomment-1443203983 as a description of the log architecture, note that each log API requests sets up its own watcher and log tailers. The log tailers can only report on new messages, i.e. what is received since they got set up. AFAIK they do not see any messages from before they existed, thus cannot report them.

The non-following logs OTOH IIRC simply ask kube for the full logs of the relevant pods/containers, and thus report past messages too.

**Comment by andreas-kupries** [comment]
> We lost the connection and an `epinio app logs --staging --follow myapp` was showing only the unpack-blob.

I had in my experiment by accident (I believe (*)) something which looked similar, however only initially.

In this setup I had run a push of the sample app, waited for the download and unpack messages to appear, and then started the  `epinio app logs --staging --follow myapp` in a separate terminal.
Both push and separate logs terminal did not print anything.
However after the build container was actually started and generating messages __both__ printed them.

I suspect, based on what I remember from the session which gave rise to the ticket, that the buildpack in question was simply in a place where it was not generating any messages for the log command to actually show. The node.js build steps in particular had several minutes of no feedback.

I recommend closing this ticket as invalid, and should it actually happen again, to look at the server logs, to confirm that the watcher/tailer setup was properly done. Because if so, then any "not printing messages" is a "not receiving messages from the pod".


---
(*) The build container took several minutes to start after download and unpack steps completed. It likely pulled a full new paketo builder image.

**Comment by enrichman** [comment]
Ok, let's close this as invalid. If we will experience it again we can reopen this.
