### ISSUE TITLE
Deploy "complex" Go web application

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2110]
We need to deploy a fairly complex Go application to get closer to our [lighthouse goal](https://gist.github.com/kkaempf/b0206c5bc85f0a8e1547912775dbc236).

Let's pick one from Github and start listing the outcomes and problems.

**Comment by andreas-kupries** [comment]
Searching `github` using `go web application`, + `language filter Go` ... Some results

  - https://github.com/benbjohnson/wtf -- https://www.gobeyond.dev/wtf-dial/ -- does not seem require services -- 3 different `main.go` entry files ...
  - https://github.com/josephspurrier/gowebapp -- see also https://github.com/blue-jay/blueprint -- the blueprint is a framework, not a full app
  - https://github.com/pluralsight-projects/golang-fifa-world-cup-web-service
  - https://github.com/lukehoban/webapp-go -- just a tiny bit more than our golang-sample-app
  - https://github.com/sohamkamani/blog_example__go_web_app
  - https://github.com/sohamkamani/go-sql-database-example (preceding + database for persistence) - postgres - db setup (tables) outside of app, db connection fixed in code -> needs tweaks for picking up a service instead.
  - https://github.com/huacnlee/mediom -- forum app - mysql, also node script ?!
  - https://github.com/aclindsa/moneygo - personal finance app - go and javascript - feels complicated to setup
  - https://github.com/disintegration/quiet - old - discontinued - db service - postgres, DATABASE_URL env.var for connection

stopped on page 7 - https://github.com/search?l=Go&p=7&q=go+web+application&type=Repositories

**Comment by andreas-kupries** [comment]
Trialed deployment of https://github.com/lukehoban/webapp-go

Final outcome: Mostly :heavy_check_mark: (:boom: app pages are 404)

Documentation:

 - https://paketo.io/docs/howto/go/
 - https://paketo.io/docs/howto/configuration/
 - https://paketo.io/docs/howto/configuration/#procfiles

Issues overcome:

  - No `Procfile`. Required.
  - Bad name for binary in the Procfile.
  - Missing HTML helper files.

Not overcome yet:

  - App pages are 404

## Procfile

The paketo go buildpack, or paketo in general, expects a file `Procfile` in the main directory of the sources. This file specifies what command to run to serve web requests, possibly with options and arguments.

It has to contain a line `web: name-of-go-binary (options, arguments)...`

Initial content was `web: webapp-go`. I.e. expected binary of same name as the go project/package.

## Bad name

The actual name of the go binary was `workspace`. The bad name prevent the server/app from properly starting.

Look for lines like
```
Assigning launch processes: 
     workspace (default): /layers/paketo-buildpacks_go-build/targets/bin/workspace 
```
in the staging log. These tell us the name of binary.
:exclamation: Note: Ignore the path. Only the name matters. The launcher/entrypoint set up by the back handles the paths.

## Missing HTML files

With the correct name in the `Procfile` the system actually attempted to launch the server.
This failed with a go panic: `panic: open edit.html: no such file or directory`.

The sources of the app contain 2 `.html` files. These are apparently required at runtime.

This was fixed by specifying `--env BP_KEEP_FILES='*.html'` for the `epinio push` command.
This may be do-able through a `project.toml` file as well.

**Comment by enrichman** [comment]
Just as a reference it seems that [Gitea](https://github.com/go-gitea/gitea) is in Go, and it looks pretty complex and famous.

**Comment by enrichman** [comment]
Here the documentation about the Gite deployment and how to: https://github.com/epinio/epinio/wiki/Gitea-deployment

**Comment by andreas-kupries** [comment]
https://github.com/epinio/epinio/wiki/Gitea-deployment

For my review and rewriting I treated the wiki page as an how-to (or tutorial)
which will go into our docs repository at some point to be an official example.


Notes and questions ...

----

```
uri = "../../buildpacks/make"
```

This (in the builder.toml) indicates that the custom build pack resides
somewhere in the forked full stack ?  Or beside it ?

Unclear, (relative) directory locations and such were not mentioned before.

----

```
Packaging the builder is done with pack:
```

Link to `pack` ?

----

```
and cannot be configured to use another
```

I added this part because the text essentially implied that this is the case,
and I wanted it to be explicit.

This note/question is just to confirm that it indeed is not possible to
configure gitea for a port other than 3000.

----

```
Check the secrets from the generated configuration
```

I am missing commands to determine the (name of the) generated configuration.
IOW the name in following command appears out of thin air.

----

```
providing all these values in the initial Gitea configuration completes the connection.
```

Missing information about where to find the gitea configuration, and how to edit it.
A file ?
Environment variables to set on push/update ?
Other ?

I assume that gitea has to be repushed/restarted when editing is done, right ?
(Which action depends on exact nature of the config and how it is edited)

**Comment by enrichman** [comment]
> https://github.com/epinio/epinio/wiki/Gitea-deployment
> 
> For my review and rewriting I treated the wiki page as an how-to (or tutorial) which will go into our docs repository at some point to be an official example.
> 
> Notes and questions ...
> 
> ```
> uri = "../../buildpacks/make"
> ```
> 
> This (in the builder.toml) indicates that the custom build pack resides somewhere in the forked full stack ? Or beside it ?
> 
> Unclear, (relative) directory locations and such were not mentioned before.
>

Yes, that's a bit unclear. A buildpack can be referenced from a docker image or locally.
I haven't pushed it, and from a developer perspective it was easier to test it without rebuild and push the image.

If you look at the [buildpack samples here](https://github.com/buildpacks/samples/blob/main/builders/jammy/builder.toml) some of them are local, while others are external:

```
[[buildpacks]]
id = "samples/ruby-bundler"
version = "0.0.1"
uri = "../../buildpacks/ruby-bundler"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"
```

Probably it's better to provide in our Epinio org a working sample that a user can clone and test


> ```
> Packaging the builder is done with pack:
> ```
> 
> Link to `pack` ?

Yes, better to add a reference to the Buildpack how-to and setup. Or explain what is `pack`.

> ```
> and cannot be configured to use another
> ```
> 
> I added this part because the text essentially implied that this is the case, and I wanted it to be explicit.
> 
> This note/question is just to confirm that it indeed is not possible to configure gitea for a port other than 3000.

It's actually possible and I did it before the custom listening port value was available, but it was a bit "ugly".
Gitea is using a `.ini` file to configure these things, so I had to do a copy and a `sed` to replace the HTTP_PORT:

https://github.com/go-gitea/gitea/blob/main/custom/conf/app.example.ini#L91

> ```
> Check the secrets from the generated configuration
> ```
> 
> I am missing commands to determine the (name of the) generated configuration. IOW the name in following command appears out of thin air.

Ah, yep. It actually came from the autocompletion, but it's worth to show that it can be found from a show.

> ```
> providing all these values in the initial Gitea configuration completes the connection.
> ```
> 
> Missing information about where to find the gitea configuration, and how to edit it. A file ? Environment variables to set on push/update ? Other ?
> 
> I assume that gitea has to be repushed/restarted when editing is done, right ? (Which action depends on exact nature of the config and how it is edited)

Yes, also this part was probably unclea. The configuration is an interactive web page that pops out the first time.

![image](https://user-images.githubusercontent.com/1763949/229104576-7fa72d00-bfa6-4998-9b2b-aab778f6d8b5.png)


@andreas-kupries as a result of the review I will create a sample repo with the forked stack, the buildpack and the builder.
What do you think? :slightly_smiling_face:

**Comment by andreas-kupries** [comment]
> It's actually possible and I did it before the custom listening port value was available, but it was a bit "ugly".

While I agree to editing/sed being ugly, I would still prefer that, just to keep chart values out of this example,
as out-of-scope/topic.

Which means that this section of the page has to be tweaked.

**Comment by andreas-kupries** [comment]
> Yes, that's a bit unclear. A buildpack can be referenced from a docker image or locally.
I haven't pushed it, and from a developer perspective it was easier to test it without rebuild and push the image.

I realized that your "fork" was simply a checkout you then edited locally.

What was not clear was if the custom (make) build pack stuff was done inside that checkout, or in a sibling directory.
The relative path as seen did not make that clear either (as the base directory it is relative to is not known to me).
This my hope for a line in the page to clarify the relative locations of things.

**Comment by enrichman** [comment]
> > It's actually possible and I did it before the custom listening port value was available, but it was a bit "ugly".
> 
> While I agree to editing/sed being ugly, I would still prefer that, just to keep chart values out of this example, as out-of-scope/topic.
> 
> Which means that this section of the page has to be tweaked.

That makes sense! I would do that.

**Comment by enrichman** [comment]
> > Yes, that's a bit unclear. A buildpack can be referenced from a docker image or locally.
> > I haven't pushed it, and from a developer perspective it was easier to test it without rebuild and push the image.
> 
> I realized that your "fork" was simply a checkout you then edited locally.
> 
> What was not clear was if the custom (make) build pack stuff was done inside that checkout, or in a sibling directory. The relative path as seen did not make that clear either (as the base directory it is relative to is not known to me). This my hope for a line in the page to clarify the relative locations of things.

Yes, actually the "fork" is a clone of the Paketo Stack, edited locally and pushed on the Docker registry.

The builder and buildpack are instead in a completely new directory. The relative references are the same because I kept the structure.
