### ISSUE TITLE
Login failed when earlier we login to another epinio server using oidc

### ISSUE THREAD

**Issue by paulgoh** [epinio/epinio#2242]
**Describe the bug**
Epinio login throws an error during login if I login to another epinio server using oidc earlier.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Login using oidc to epinio-server-A, i.e., epinio login --oidc https://epinio-server-A
2. Now login without oidc to epinio-server-B, i.e., epinio login https://epinio-server-B
3. You might see this error:
❌  error verifying credentials: error while connecting to the Epinio server: Unauthorized: token verification failed: verifying rawIDToken: oidc: id token issued by a different provider, expected "https://epinio-server-B" got "https://epinio-server-A"
4. Sometimes you might see this error, although I don't know how to reproduce this error:
❌  error verifying credentials: error while connecting to the Epinio server: invalid character '<' looking for beginning of value

**Expected behavior**
I do not expect to see an error when I login to different epinio servers.

**Logs**
(base) ➜  app-server git:(main) ✗ epinio login https://epinio-server-B

🚢  Login to your Epinio cluster [https://epinio-server-B]

Username: epinioadmin
Password: 

❌  error verifying credentials: error while connecting to the Epinio server: Unauthorized: token verification failed: verifying rawIDToken: oidc: id token issued by a different provider, expected "https://epinio-server-A" got "https://epinio-server-B"

**Cluster (please complete the following information):**
 NA

**Desktop/CLI (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - Epinio Version: 1.7.,1
 - Epinio Install Options: NA

**Additional context**
NA

**Comment by gitricko** [comment]
I think we should have a logout command... and when a user issue a login command, we should do a logout first so that the settings yaml/json are clear out.

This is an issue that developer will spend lots of time figuring out. Especially, in a multi epinio env (dev, test, prod) We can get into this issue very easily. It will give a user a bad dev experience. (not as bad if we use raw k8) but still confusing and frustration for the user

**Comment by enrichman** [comment]
Reading again this issue I understood which is the problem. The bug is related to the priority of the two tokens in the settings. Basically if user, password and token are all available the token will be the one used, instead of the last one.

We should cleanup the old login settings after a successfull login. Anyway the logout command make sense!

**Comment by mmartin24** [comment]
Checked  in `v1.8.0-23-ga8964680`, using single node k3d and Minkube deployments and oidc login on the first one:

Before (error):
![login_error_2_servers](https://github.com/epinio/epinio/assets/37271841/9e023f53-0ea5-411f-aee7-db97f705f7dc)


After (fixed):
![login_2_servers_fixed](https://github.com/epinio/epinio/assets/37271841/07aa742f-f71f-43f0-9924-781079f2e097)

**Comment by mmartin24** [comment]
verified again in `v1.8.1-rc1`:
![image](https://github.com/epinio/epinio/assets/37271841/761e28bb-9841-4c67-bd45-49bda944c270)
