### ISSUE TITLE
Version info should be a command instead of flag

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#245]
I should be able to run `carrier version` to get the version of the client that I'm using

*Or*

`carrier info` could return client version as well as server versions (then carrier version could be a subset of that data?)

Also, this should be found in `carrier help` as well

**Comment by jimmykarily** [comment]
`epinio version` exists since https://github.com/epinio/epinio/commit/e7e62fe64553025fdccb64d4f85b468b5c9bd218

(it's allso a flag `--version`, both work)
`epinio info` return a version but it's not in the format: server version/ client version
it just prints one version (not sure which one that is).

Given the description of this issue, I consider it done. Feel free to open a new one for the `epinio info` output.
