### ISSUE TITLE
Have the possibility to not use certmanager

### ISSUE THREAD

**Issue by yodatak** [epinio/epinio#2476]
**Is your feature request related to a problem? Please describe.**
In my entreprise k3s cluster we don't have let's encrypt connection and we just have a wildcard cert so we don't need cert manager but it's a requirement for epinio

**Describe the solution you'd like**
Have the possibility to install Epinio without cert manager and support tsl cert file

**Comment by andreas-kupries** [comment]
Basic check: Install E without a cert-manager on the cluster.
Result:
```
Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "epinio" namespace: "epinio" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "minio-cert" namespace: "epinio" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "epinio-ca" namespace: "cert-manager" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "epinio-registry" namespace: "epinio" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "selfsigned-issuer" namespace: "" from "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "epinio-ca" namespace: "" from "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
ensure CRDs are installed first]
```

E chart uploads a number of cert-manager.io/v1 resources. Without the cert-manager (CRD) present that fails.
Step I: Exclude these resources.

**Comment by andreas-kupries** [comment]
With the cert-manager resources disabled a number of secrets are missing (IOW those which are generated from the cert resources by cer-manager):

- dex-tls
- epinio-registry-tls
- epinio-tls
- epinio-ui-tls
- minio-tls

These secrets have to be created as regular resources when the cert-manager is not present.

**Comment by andreas-kupries** [comment]
Beware: The standard application chart also make use of `cert-manager` Certificate resources.
Namely to set up the tls secret for the app's ingress.

**Comment by andreas-kupries** [comment]
> Beware: The standard application chart also make use of `cert-manager` Certificate resources. Namely to set up the tls secret for the app's ingress.

Having slept over this we actually have a way for this already. Our `Routing secrets`.
See https://docs.epinio.io/references/customization/routing_secrets
The operator has to provide one more secrets for the app domains
Epinio will automatically use them for matching domains.
And the cert-manager certificates in the app chart are disabled in favor of that secret.

**Comment by andreas-kupries** [comment]
As a summary, and possible specification:

1. Enable the disabling of cert manager by setting the `.Values.certManagerNamespace` to the empty string (not leaving it out, that would be null). Change templating to react to this by excluding all the `Certificate` resources.
2. Extend the E chart with kube `Secret` resources for all the excluded certificates. Activate them in templating when the cert manager is disabled.
3. Extend the `values.yaml` with variables for the content of the Secret keys (`tls.crt`, `tls.key`, and `ca.crt`) and change the chart to template them in. This enables the operator to insert their cert(s) on installation.
4. Question: Expose each Secret separately ? It would be easier to expose only one set of variables for this, and simply use them in all the new secrets.
5. Document that the operator __is forced to use routing secrets__ in this mode to bypass the ingress `Certificate` in the standard app chart.
6. Actually the operator could create a non-standard appchart instead, which uses a `Secret` instead of a `Certificate` and making that the default in the E installation. Basically having the necessary routing secret(s) baked in. This would obviate the need for the operator to put the routing secrets into all possible namespaces. The appchart would do it for the developer.

@enrichman Your thoughts and opinions ?
@yodatak Ditto.

**Comment by enrichman** [comment]
> As a summary, and possible specification:
> 
> 1. Enable the disabling of cert manager by setting the `.Values.certManagerNamespace` to the empty string (not leaving it out, that would be null). Change templating to react to this by excluding all the `Certificate` resources.

The `certManagerNamespace` in the Rancher installation question.yaml is not required:

```yaml
- variable: certManagerNamespace
  label: Cert-manager namespace
  description: "Namespace where cert-manager is installed in"
  type: string
  required: false
  group: "Advanced settings"
```
so I would prefer having a more explicit and consistent flag, like the other that we have for Minio, Dex, or 

```yaml
minio:
  enabled: true

epinioUI:
  enabled: true

kubed:
  enabled: true

s3gw:
  enabled: false

containerregistry:
  enabled: true

global:
  dex:
    enabled: true
```

> 2. Extend the E chart with kube `Secret` resources for all the excluded certificates. Activate them in templating when the cert manager is disabled.
> 3. Extend the `values.yaml` with variables for the content of the Secret keys (`tls.crt`, `tls.key`, and `ca.crt`) and change the chart to template them in. This enables the operator to insert their cert(s) on installation.

Usually the `tls.crt` and `tls.key` are enough, the `ca.crt` is needed only with custom CA, and it needs some work on the application side, so maybe we don't need that. We can also add a more generic "tlsSecretName" to provide the secret with the cert, I find it more ergonomic. Having a look at other charts they have sometimes both of the options.

> 4. Question: Expose each Secret separately ? It would be easier to expose only one set of variables for this, and simply use them in all the new secrets.

It's probably possible with some of the secret, not sure if it's doable for all of them. I.e. the Dex secret is the one for the `auth.*` endpoint, the registry is an internal one, and epinio is on the `epinio.*`. So for those you can probably expose the wildcard cert, but the registry needs a different one. Also if you are using an external registry you can skip this part, and you need a different secret.

Be aware for the subchart that we should stick to their implementation, when possible. I.e. for minio there is already a way to provide the secret, we just need to drop the cert-manager, and expecting the secret to have been already created by the user.

```
minio:
  tls:
    enabled: true
    certSecret: minio-tls
```

We just need to document that if you are using Minio without cert-manager the `minio-tls` secret won't be there, and you need to create it upfront. Or provide the right secret name. Or drop Minio and use your S3.

> 5. Document that the operator **is forced to use routing secrets** in this mode to bypass the ingress `Certificate` in the standard app chart.
This is the way. :+1:  If we already provide a way, just continue with this.

> 6. Actually the operator could create a non-standard appchart instead, which uses a `Secret` instead of a `Certificate` and making that the default in the E installation. Basically having the necessary routing secret(s) baked in. This would obviate the need for the operator to put the routing secrets into all possible namespaces. The appchart would do it for the developer.
> 
> @enrichman Your thoughts and opinions ? @yodatak Ditto.

To finalize a bit regarding the secrets:

- minio-tls (it should be "already done")
- epinio-registry-tls (this is internal and different from the other host.. :/ )

This can be probably handled with the same, but this means that it has to be a wildcard, or not? 
- dex-tls
- epinio-tls
- epinio-ui-tls

One thing that we can probably do upfront without any problem is "merging" the two latest secret. I guess that they were separated because the two were two different charts, but they can probably be merged into one secret with two dnsNames. Basically dropping the `epinio-ui-tls`, in favor of a single `epinio-tls` with this spec:

```
spec:
  dnsNames:
  - {{ .Values.global.domain }}
  - epinio.{{ .Values.global.domain }}
```

We can try this as a first iteration. One secret less that we should care about.
