### ISSUE TITLE
Add git proxy endpoint

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2490]
To add on the UI (or also CLI?) the possibility to use authenticated requests for the git APIs we need to add an endpoint can be used with authenticated requests. 

Depends on https://github.com/epinio/epinio/issues/2488

There is something in the old Stratos repo (https://github.com/epinio/ui-backend/blob/main/src/jetstream/passthrough.go#L378) but it's probably outdated.

It should be enough to have a request object containing:

```json
{
    "url": "https://github.com/repo/bla/search",
    "method": "POST",
    "body": "{\"foo\":\"bar\"}",
    "headers": {
        "X-Some-Header": "header-value"
    }
}
```

**Comment by andreas-kupries** [comment]
> to use authenticated requests for the git APIs 

What exactly does this mean ?
That the Web UI can perform the equivalent of `git push`, `... pull`, ..., etc. ?
If yes, in what context is that needed/useful ?

**Comment by enrichman** [comment]
Git APIs is a bit confusing. I'm referring to the Github/Gitlab APIs. The UI is already performing some requests to retrieve some information (i.e. the available repositories of a user/org. Passing through a proxy could a server-side authentication increasing the rate limiting, or accessing some private information, while storing the secret/tokens securely.

**Comment by enrichman** [comment]
@richard-cox @torchiaf

I'm having a look at this, and I have a working implementation. There's only one thing that we should agree on.
IIRC we have said that it will be nice to let the user select the `gitconfig` to use. If we agree on that I would add a `gitconfig` field that can be used to select the proper Git Configuration, with the credentials that can be used to authenticate with the provider.

Another approach would be trying to look for and "guess" a configuration with a matching URL, but it could not work (maybe the PAT that was there doesn't have access to some repository).

One more thing regarding the security of this `/gitproxy` endpoint.  
I dont think you need to provide any headers or body to the URL. And also the methods seems to be only `GET` to do some queries, so I would drop the three fields and keep it simple. We could add them later if we need to.

```json
{
    "url": "https://github.com/repo/bla/search",
    "gitconfig": "my-git-config"
}
```

Also I'm not sure if I should validate and restrict the set of endpoints to proxy, checking the path.

What do you think?

**Comment by richard-cox** [comment]
> IIRC we have said that it will be nice to let the user select the gitconfig to use
Agree, the user would select their gitconfig when setting the app source in the create app flow. Anything git related to that source would then use that gitconfig (the UI would provide the proxy request with the gitconfig from the app). That would also extend after the create flow (for example user views the git info in the view app context). So that gitconfig would need to persist and be available to the UI in a similar way to the git type of the source. Haven't checked the implementation / CLI, is that roughly how it currently works?

> Another approach would be trying to look for and "guess" a configuration with a matching URL
The user would then also be restricted to a single token per type. Would agree we should try to avoid the automatic detection.

> I  dont think you need to provide any headers or body to the URL
Think this is fine. @torchiaf can confirm, but we don't send anything in headers (need to check for pagination information) and only use GETs

> Also I'm not sure if I should validate and restrict the set of endpoints to proxy, checking the path.
Nice to have. I think we're settled on the API requests the UI makes now.  @torchiaf can you check the http requests the UI makes to both github and gitlab and provide the paths?

**Comment by richard-cox** [comment]
I really need to look at the config, but from our view point is it not a combination of URL and token? Was wondering if the proxy config would just be `path` and `gitconfig`

**Comment by richard-cox** [comment]
Ah, think i forgot the discovery discussion. 

So for round one the user will select a git config in the app create / edit world just to discover git details to supply. When requesting git details (via proxy) for an existing app's source it will provide a url (which is in the app details) and Epinio will find a gitconfig to use. 

I think at some point it would be nice for the user to explicitly decide which config to use, but as a first step the above should work
