### ISSUE TITLE
[backend] String values are saved with double quotes in Chart values/settings 

### ISSUE THREAD

**Issue by torchiaf** [epinio/epinio#2510]
Related PR: https://github.com/epinio/ui/pull/300#issuecomment-1673179636

**Comment by andreas-kupries** [comment]
I suspect that the issue is the fact that the server is not storing the incoming CV data as-is somewhere where it can be returned without effort. Instead it tries to ~heuristically~hackishly reconstruct the CV data from the helm release of the server. And returns JSON data, instead of the incoming plain strings, for the more complex structures (nested maps, arrays, maps in arrays, ...)

Plan to fix:
- Store the CV data in the service secret. Return it from there when asked.
- Keep the heuristic reconstruction for backward compatibility with 1.9.0-created services which will not have this stored CV data.
