### ISSUE TITLE
Split tests ...

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#263]
... for parallelization, more focussed test areas, and speedup.

To be tackled post-mvp

**Comment by jimmykarily** [comment]
We have tests that install/uninstall Epinio or some components. As far as I can tell, these are [the features tests](https://github.com/epinio/epinio/blob/main/acceptance/features_test.go) (which enable/disable in-cluster services etc)

There are also other tests that [enable the components](https://github.com/epinio/epinio/blob/main/acceptance/catalog_services_test.go#L15) if they are not there already but never disable them. That mean we could simply enable those components in the BeforeSuite block.

All other tests can safely run against the same Epinio instance (and the same Kubernetes cluster). That means we don't need GINKGO_NODES number of clusters but just one. Enabling in-cluster services is optional because it will probably never be used in production environments. The gke service is optional because it need configuration (auth) that only the users who want to use google cloud will have available thus it makes no sense to do it in `epinio install`.

We need to find a way to run the tests that mutate the cluster serialized somehow and on a separate cluster (ginkgo doesn't seem to support this yet: https://github.com/onsi/ginkgo/issues/526). We can run all the rest in parallel on the same cluster. This limits the number of clusters we need to just 2. The mutating tests are not expected to grow as much as the other tests so it's sane to expect this to keep working for a while.

An option would be to separate the mutating tests to a new test suite.
