### ISSUE TITLE
`service create` is expecting the Service `name` from the metadata field

### ISSUE THREAD

**Issue by enrichman** [epinio/epinio#2699]
**Describe the bug**
When trying to create a service created with a different name from the one specified in the `name` field it will not work. It's looking for the name in the metadata field instead.

**To Reproduce**
1) create a service with a different name (metadata vs spec):

```yaml
apiVersion: application.epinio.io/v1
kind: Service
metadata:
  name: simplenginx
  namespace: epinio
spec:
  name: nginx
```

-> `simplenginx` vs `nginx`

2) the service catalog will show the name in the spec:

```
-> % epinio service catalog                           

🚢  Getting catalog...

✔️  Epinio Services:
|      NAME      |            CREATED            | VERSION |          DESCRIPTION           |
|----------------|-------------------------------|---------|--------------------------------|
| nginx          | 2023-11-15 18:02:34 +0100 CET | 15.2.0  | A Simple nginx                   |
```

3) trying to create with the `nginx` name

```
-> % epinio service create nginx mynginx --wait 

🚢  Creating Service...
Catalog: nginx
Service: mynginx
Wait For Completion: true

❌  error creating service: service create failed: error getting service nginx from namespace epinio: services.application.epinio.io "nginx" not found
```

4) using the `simplenginx` from the metadata works
```
-> % epinio service create simplenginx mynginx-rr --wait

🚢  Creating Service...
Catalog: simplenginx
Service: mynginx-rr
Wait For Completion: true
```

**Expected behavior**
The exposed `name` should be used, because it's the one exposed in the catalog.

**Comment by andreas-kupries** [comment]
The standard services avoid this issue because for them `metadata.name` and `spec.name` match.
(Which means that technically we can claim that `metadata.name` is the exposed name)

The code retrieving a service avoid a `List`-query, by using the `serviceName` directly as the resource name, i.e. `metadata.name`. See

https://github.com/epinio/epinio/blob/96ce9dbcb7888ea02a2e5470b1279f584bd168ae/internal/services/catalog.go#L41-L43

The easier fix would be to change function `convertUnstructuredIntoCatalogService` to put the `metadata.name` in as the servicename, replacing `spec.name`.

The asked-for fix requires a list query with either filtering through ListOptions, or a go loop over the returned set.

Interestingly nobody external has reported this. Either they all use the standard services, or any custom services follow their example and use matching names for `metadata.name` and `spec.name`.

**Comment by andreas-kupries** [comment]
ListOptions allow LabelSelector and FieldSelector.
The service catalog entries have no labels to filter by, and it would be a third place for the service name, anyway.
FieldSelectors are highly restricted on what fields filtering is possible.
See https://github.com/flant/shell-operator/blob/8fa3c3b8cfeb1ddb37b070b7a871561fdffe788b/HOOKS.md#fieldselector
`spec.name` for a CRD is not filterable.
Explicit loop it will have to be.

**Comment by andreas-kupries** [comment]
That said, another point against request fix:
- `spec.name` is not guaranteed to be unique. Using it requires us to do as we recently did for users ...
  Find and drop definitions with conflicting names. Or just make them not usable. IOW more complexity.

The easier fix becomes more tempting. Because `metadat.name` is unique, enforced by K.

**Comment by andreas-kupries** [comment]
Two competing solutions:
- #2709 
- #2710 

I prefer 2710 as the simpler solution with less baggage.
