### ISSUE TITLE
Replace omg.howdoi.website with an `epinio.io` subdomain

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#271]
@colstrom do we need a second deployment of that service or can we use the same instance and point one more domain to it?

**Comment by colstrom** [comment]
Hey, my apologies for the delayed response.

Looking at the [relevant section of the backend code](https://github.com/exentriquesolutions/nip.io/blob/master/nipio/backend.py#L209-L219), it only supports one domain per instance.

What's the intended audience for this service? Is this purely an internal thing, or local development only, or used in default deployments or something? If (when) it breaks, who becomes sad? How do they cope with an outage? Does it block them from doing things, or can they resolve it with a config change or something? Does that change require redeployment? Do the DNS names end up embedded in some routing rules, databases, auth headers, etc?

Deploying another instance is possible, but the support expectations that go along with that would make a difference in how/where it gets deployed.

Thanks in advance for any details you can provide.

**Comment by manno** [comment]
Hey, @colstrom 
We want to replace the omg.howdoi.website. This will be in the README and we have logic, which decides that using that domain indicates a dev deployment.

https://github.com/epinio/epinio/blob/main/internal/cli/install.go#L13

So, DNS is cached. Shouldn't be too bad if it's down for a day.

**Comment by kkaempf** [comment]
Could https://nip.io be an alternative ?

**Comment by andreas-kupries** [comment]
IIRC we went explicitly away from `nip.io`, because of `nip` being a slur against Japanese.

**Comment by jandubois** [comment]
> because of `nip` being a slur against Japanese.

https://en.wikipedia.org/wiki/Nip

**Comment by jimmykarily** [comment]
https://github.com/epinio/epinio/issues/101

**Comment by jimmykarily** [comment]
@colstrom this domain will only be used for demos and development. It doesn't have to be linked to Epinio in any way (no need to be a subdomain of epinio.io) and shouldn't look official in any way. There are other alternatives on how to make the out of the box experience better for the user (e.g. what rio does with the subdomains) so this feature may not stay forever.

That said, any domain that doesn't look weird (like `omg.howdoi.website` does) and doesn't offend anybody (like `nip.io` may do) should be ok. The only requirement is that it's a domain that doesn't draw people's attention during demos, because we want people's attention on other things.

**Comment by andreas-kupries** [comment]
Subdomain ideas:

  - `demo.epinio.io`
  - `unsupported.epinio.io`
  - `trial.epinio.io`
  - `sandbox.epinio.io`
  - `example.epinio.io`

Ok, running out of ideas.

**Comment by jandubois** [comment]
> Subdomain ideas

Just for reference, here are the things we mentioned in CAP standup yesterday:

* don't use a `*.dev` domain because browsers **force** all connections to https with them
* don't use a subdomain of the project because you don't want others to showcase unrelated stuff with the project branded name. You have no control over what people will do; externally it is just an alternative for `[nx]ip.io`.
* avoid using a domain controlled by SUSE IT because then your are subject to "freeze windows" where **no** changes can be made to DNS for 2 weeks at a time, so if anything is broken, you would be out of luck to fix it

**Comment by kkaempf** [comment]
That doesn't leave many options. And xip.io [is also broken](https://github.com/rancher/rancher/issues/32500)

**Comment by jandubois** [comment]
> That doesn't leave many options. 

How so? There are an endless number of domains available that we can purchase for little money. If we can host it under `omg.howdoi.website`, we can also host it under `magicdns.io` or any other name that has neither `suse` nor `rancher` nor `epinio` as a substring.

You just don't want your project name in a URL like `piratebay.123.134.145.156.epinio.io` (totally made up example, but you couldn't prevent people from using it for that).

The comment about `*.dev` came about because somebody suggested to use a `*.suse.dev` subdomain, but `*.dev` is on the [HSTS preload list](https://hstspreload.org), so won't allows HTTP connections from browsers. Don't use any domain that is registered on the preload list; you will regret that later...

> And xip.io [is also broken](https://github.com/rancher/rancher/issues/32500)

Yes, that is the sole reason `nip.io` was created. Its original website said:

>nip.io is a blatant rip-off of xip.io, with one big difference: NIP.IO is powered by PowerDNS with a simple, custom PipeBackend. So, it actually works 	:slightly_smiling_face: (no messy, custom DNS server here!)

**Comment by mook-as** [comment]
Hi! Just wanted to point out that using things as a substring is okay, as long as it isn't a subdomain: GitHub Pages run on `github.io`, because they don't care if cookies get messed up there; all actual authenticated stuff happens on `github.com`.  So `epinio.website` would totally work, for example.

**Comment by jandubois** [comment]
I still think avoiding the substring is a good idea for brand protection reasons (but anybody can use the substring in their own DNS names anyways, so this is not a strong argument).

> they don't care if cookies get messed up

Thank you for bringing up the cookie issue; I didn't think about that! So there might also be security concerns as well.

**Comment by vincent99** [comment]
As you linked above, Rancher has the same problem so if you're going to run one we would be interested in using it (vs switching to`nip.io`) too.  I would suggest something as short and generic as possible, e.g. `byip.io` is available.

We do have several similar branded things (`on-k3s.io`, `on-rio.io`, `on-rancher.cloud`) but they involve making an API call to get & periodically renew a name "lease" vs being pure mechanical DNS mapping.

As far as security:
 - You definitely want a new domain and not a subdomain of one already used for _anything_ else because subdomains will be able to read cookies set by the parent domains.
 - There are also lesser problems with cookie security across the generated names you'll give people.
 - The best thing would be to get it added to the [PSL](https://publicsuffix.org/) ([example from us](https://github.com/publicsuffix/list/pull/779)).
 - And use hyphens instead of dots (`optionaltext-123-134-145-156.byip.io`) so it's a flat single namespace.  They kinda say you could add `*.*.*.*.byip.io` to handle dots, but you [can't really](https://github.com/publicsuffix/list/pull/879).

**Comment by agracey** [comment]
@jimmykarily Can this be closed with the completion of https://github.com/epinio/epinio/pull/613?

**Comment by jimmykarily** [comment]
Since #590 we no longer base our decisions on which issuer to use and how to expose the internal registry to the domain `omg.howdoi.website`. This means the user can use whatever domain they want with any of the provided certificate issuers (epinio-ca, self-signed or lets-encrypt). Still, when the use doesn't define a domain, we are using `omg.howdoi.website` as a way to quickly test or demo Epinio with as little `epinio install` parameters as possible.

Changing a domain that works like `omg.howdoi.website` but is "prettier" would be good but not necessary anymore.

**Comment by agracey** [comment]
Ok, I'm going to pull the beta tag off and you can discuss closing at a planning meeting.

The reason I had it there was that omg.howdoi.website didn't work for DNS provided by some ISPs. Now that a switch to another dns doesn't come with loss of functionality, it's not needed any more IMO

**Comment by agracey** [comment]
Is there any objection to closing?
