### ISSUE TITLE
Check usage of `registry-tls` cert

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#342]
The `registry-tls` is used by something.
Unclear if the name is still sensible based on the user.
Unclear if it could be replaced by the `registry-tls-self` cert.

Needs a bit of investigation and experimentation.

This is a followup to #298 and its PRs #340 and #341

**Comment by jimmykarily** [comment]
I'm getting rid of one more instance of registry-tls here because I couldn't find it being used: https://github.com/epinio/epinio/pull/453/files#diff-388ac05c39a6a0be16fbd7a77118244e591938a4626a0b76348a5240cc41bb01L124

@rohitsakala you said this you removed `registry-tls` from other places and things still worked right? This is probably a left-over that need cleanup. We still need to investigate and document the remaining `registry-tls-self` in code, so we don't wonder again where it's used and for what.

**Comment by rohitsakala** [comment]
Based on current code observations, we removed `registry-tls-self` secret long back and are using `registry-tls` (current name is `epinio-registry-tls`) This certificate is used as a mount on tekton so that tekton can recognize the registry when it does HTTPS push to the registry.

Made a small PR for refactoring #717
