### ISSUE TITLE
Allow deployment template to be customized

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#361]
It would be very helpful to give an escape hatch to deploy custom yaml as part of the workload being deployed

Some usecases:
- Adding NetworkPolicies to app
- Adding HPA to app
- Adding custom sidecars 
- Deploying built container to knative
- Class of service differences in deployments

This feature is a foot-gun but if we don't expose it through the CLI and require manual editing of a ConfigMap, then it's the Operators responsibility to write good templates. We can even say that if the template is changed, we no longer guarantee the stability of workloads.

- [x] #1224

**Comment by agracey** [comment]
The assumption being that the user has permissions to create the objects being requested

**Comment by agracey** [comment]
This could be doable with "class of service" templates to make safer

**Comment by agracey** [comment]
Formalizing the request slightly:

I would like to be able to customize the yaml that gets deployed when I push an app. It would also be very valuable to developers to allow a different template selection when pushed (but has a default). 

This is likely best done by having a CRD that defines a template to be filled in.

**Comment by jimmykarily** [comment]
We had a short discussion about this and about use cases. The use case as we understand it, is this:

Some operator, familiar with kubernetes, has a strong opinion on how an application deployment should look like. Maybe also, that operator is not satisfied with how Epinio deploys apps or maybe what we do is not enough and doesn't cover their needs.
That operator still wants to have the "epinio experience" with `epinio push` and all. The cluster's users will be developers and they don't have to know how the application is deployed.

Now a fact:

Epinio application deployment is just a Deployment exposed through a Service and an Ingress. Also uses some auto-generated certificates for TLS.

From all the above, the only things that change (unless I'm missing something) are, the Deployment's container image (which is the staging artifact), the application route (for the Ingress) and some labels on the various resources (the name of the app, the org etc). The rest are really just a template and they are similar in all apps.

The application resources described above used to be templates in the Tekton Pipeline, then we moved them to go code. In any case, conceptually, they are still templates with some values interpolated.

Now, here comes an idea we came up with:

What if Epinio used a default helm chart for the application deployment. That helm chart would have all the needed resources and the different values for each application would be helm values. The operator would simply have to follow the same contract (provide the same values, we can even validate that) and replace the application helm chart Epinio is using. Being a helm chart (and not some strange code flow we follow to generate the application resources) means, the operator can test the helm chart they maintain, on their own CI and make sure, whatever Epinio is going to do with it, will work (e.g. `helm install`, `helm uninstall`, try various values etc).

This allows us to:

- Have a strong contract and be able to control the created resources (e.g. uninstall the app correctly)
- Have an easy way for the operator to replace that template. They even have a starting point to start tweaking, our default template.
- We can easily implement features like:
  - Download the applications helm chart to be deployed outside Epinio (or even as backup)
  - Promote the app to production (by appying the same helm chart)
  - Integrate with Fleet (by committing the helm chart to a fleet repo instead of applying it)
- Support different application helm charts (and thus deployment types) per app or per namespace.

This has the drawback that we need to integrate `helm` inside Epinio somehow, hopefully as a golang library. That might bring in too many dependencies and make version upgrades hard.

Note: we can even store the application helm chart on our (newly implemented) S3 storage on some bucket, to make it easy to replace and try out things.

**Comment by kkaempf** [comment]
> This has the drawback that we need to integrate helm inside Epinio somehow, hopefully as a golang library. That might bring in too many dependencies and make version upgrades hard.

I heard the [Hypper](https://github.com/rancher-sandbox/hypper) people have some experience with embedding `helm` :wink:

**Comment by jimmykarily** [comment]
Looking at how Hypper integrated with `helm` (https://github.com/rancher-sandbox/hypper/blob/main/cmd/hypper/install.go) I start thinking that maybe it's better if we just implement the `helm install` step as a Tekton Pipeline. We already have a way to collect and stream pipeline logs to the user (from the staging pipeline). Also we won't need to neither shell out to helm nor integrate it.

Anyway, that's up to the implementation. Let's see if we like the idea first.

**Comment by agracey** [comment]
I like @jimmykarily's suggestion and personally think moving the install step back inside Tekton makes the most sense as it decouples any logic there from the API code (which I would imagine reduces future maintenance cost?)

**Comment by manno** [comment]
After discussing this, we decided not to continue with helm as a template engine (PR #851). Switching Epinio to use a PipelineRun to run helm for at least deploy/uninstall/update introduces many problems. It's unclear if helm is the right extension mechanism for our application template.

**Comment by andreas-kupries** [comment]
Looking at this and the discussion in the comments it seems to me that the entire preceding discussion is moot, as it refers to things which do not exist any longer. I.e. tekton is gone, replaced by a kubernetes Job directly calling on the Paketo buildpack (standard builder image) to convert app sources to runnable app image.

The deploy operation itself still creates the trinity of Deployment/Service/Ingresses, via Go code.

In light of the changes to staging, what are the current thoughts from @epinio/epinio  about the proper templating now ?

  - Is a template `helm chart` again a possibility ? It would require use of helm directly from the API server, instead of indirectly through Tekton.
  - Or, should the D/S/I trinity configuration be moved into a config map to be templated via basic %-placeholders and then applied with the go equivalent of `kubectl apply -f` ? Note that the config map would hold the configuration as YAML __text__!
  - Any other possibilities ?

**Comment by andreas-kupries** [comment]
The ingresses are actually somewhat of a problem. While mostly generate a single ingress for the single app route, we do support multiple app routes, and the go code generates multiple ingresses for that.

The templating has to take that into account.

I currently see no problems for the two possibilities brought up so far (helm chart and config map). Either can use the go templating language to iterate over the routes information to generate multiple ingresses from the template.

**Comment by agracey** [comment]
Another benefit to deploying the app with helm is that it will show up in Rancher under "Installed Apps" which could lead to better portability of the apps built with Epinio. 

I don't think writing a helm chart that deploys multiple ingresses should be that hard if we structure the values.yaml that we push in well.

**Comment by andreas-kupries** [comment]
I did not think so either, note my note about iterating using the template language.

**Comment by andreas-kupries** [comment]
Reading a bit more through the go client mentioned above it seems it can install a chart from url, i.e. a remote tarball independent of a repository. I.e. it could be done by direct access to the https://github.com/epinio/helm-charts/releases ... The issue there would of course be versioning ... Hm ... https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases mentions an url for direct access to latest ... Limits the asset name however, i.e must be unversioned.

**Comment by andreas-kupries** [comment]
Done with the epic. Re-open if we find something new later, or start a new epic/issue for that.
