### ISSUE TITLE
Signing Containers on Build

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#417]
For users concerned about supply chain security, it would be awesome to sign containers with a provided private key.

**Comment by jandubois** [comment]
This is a bit more complex topic than just signing a container with a key. You would also need a mechanism to make sure that all inputs have been validated to come from a trusted source. So all sources must come from a version control system and have their commit id confirmed. The buildpacks used must also have an unique signed identity, and all this metadata about the pieces that were used to build the container must be stored inside the container, and covered by the container's signature.

So when you later audit a container, you can trace it back to the sources used to build it, and the tools.

Of course to be really trustable the buildpacks must package all additional software that is not included/vendored in version control; if you pull e.g. from NPM during a container build, no amount of signing will allow you to verify the heritage of the code within.

I know that most tools don't support it yet, but ideally you should be able to produce identical container builds by just using the same source checkout and buildpack that has been recorded in the container metadata. This would also allow you to update a container with security fixes and be confident that not much else has changed during the rebuild. 😄 

Furthermore there is the question of protecting the signing key. You also must make sure an attacker cannot abuse your system to sign a malicious container image. Locking down builders to pulling source code from a fixed version control system instead of letting the user provide it directly will help a bit.

Anyways, this is not a small/simple feature, but I agree it would be awesome if it could be made to work.

**Comment by agracey** [comment]
Totally. It's not just the signing but this was the first of a set of issues for a full security story! 

Eventually, I'd like to see a fully auditable code trail (including signing from the user that started the push). One of the places where we might be able to do something interesting is if buildpacks use an artifactory or nexus to give some control over libraries being pulled in by npm.

**Comment by jandubois** [comment]
One idea I've been sometimes pondering is if the container shouldn't (optionally) include a tarball of all the sources used to build it, as an alternative to a commit id of an external version control system. It could (maybe, optionally?) encrypt the sources with a private key, if this is a concern, but I suspect that isn't important.

That way you could always rebuild the container from the embedded sources, plus a copy of the buildpack. I like this idea because links to version control are inherently brittle because things get moved around/rebased/lost/whatever. And this method works even when the sources are not in version control...

This also makes it very simple to include a signature of the user submitting the sources to be built.
