### ISSUE TITLE
Upstream authentication

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#425]
We will need to give some ability to plug into common IDPs.

**Comment by jimmykarily** [comment]
Part of #486 ?

**Comment by agracey** [comment]
If this can be "Rancher Auth" then we get any upstream that Rancher can provide

**Comment by agracey** [comment]
From Victor: https://cerbos.dev/ Might be an interesting way to approach this.

**Comment by jimmykarily** [comment]
The title of this issue talks about "authentication" (multiple users). `cerbos.dev` seems to be about "authorization" (user permissions). Upstream authorization is something like "I want to login with GitHub". Upstream authorization could mean something like "I want that Epinio user to be able to do whatever that serviceaccount (in kube) is allowed to do".

I think authorization deserves a new issue, unless there is already one.

On a first look, cerbos looks nice and it proves that it's not that hard to define arbitrary permissions that match Epinio's domain logic (e.g. we define permissions on "applications" rather than "deployments", "pods" etc).  Personally I don't see much value in upstreaming "authorization" to kubernetes. Something like cerbos makes more sense.

**Comment by enrichman** [comment]
I guess that this can be closed:
- #1571
