### ISSUE TITLE
Create/manage extended namespace names for epinio organizations

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#434]
When creating an org in epinio, we create a namespace with the very same name - and esp. fail, if that namespace already exists.
E.g. users can't create an organization named "quarks", aso.

It would be nice, if we could e.g. just extend the resulting namespace names, in order to give more freedom with organazition names to users:

e.g. creating org "quarks" would result in a namespace "epinio-quarks", and just be managed accordingly

That would still, or even be more user readable from the operator side.

**Comment by svollath** [comment]
... and of course, it would start with workspace -> epinio-workspace :)

**Comment by jimmykarily** [comment]
One thing to consider is the maximum allowed length for Kubernetes objects. In most cases, the Epinio user will see an error if they try to create an object with a name that exceeds that limit. Prefixing resource names reduces the number of allowed characters for the user. We could untie ourselves from those limitations if we consistently generated valid UIDs (<63 characters) for all objects and used annotations for the human readable name. Annotations don't have a character limit afaict (labels do: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).
On the other hand, finding objects by annotation is not going to be very efficient (that's what labels are for and that's why their length is limited). Also it's going to complicate the code in many different places. E.g. anywhere an org name is used, we will need to do a lookup to find the actual namespace name.

Another option is to only support org names which are `63-16` in length (16 is the number of characters in `epinio-workspace`).

**Comment by svollath** [comment]
True, it would restrict max. characters to 63-7 (epinio-) - I just meant we should start to make the default workspace epinio-workspace. An org called quarks should end up in a namespace epinio-quarks, so 63-7 ...

**Comment by svollath** [comment]
Just for comparison - a cf org could hold 255 chars.
Also a bit similar is https://github.com/cloudfoundry-incubator/eirini/issues/62.

So one (let's make the code more complicated) solution could be
- Allow 63, or up to 255 chars for epinio ORG names
- make the related kubernetes namespace start with "epinio-", to sort the output of ORG around 'epinio-'
- if an ORG name exceeds 63-7 chars, it will get cut at char 49 and extended by "-<random 6 digit>"

That would mean, epinio ORG would support e.g.:
- "grouped listing" in kubernetes
- ORG names that exceed 63 chars, e.g. up to 255
- up to 56 chars human readable as kube namespace
- 49 chars human readable if the ORG name exceeds 56 chars

This would totally support human readable style, until someone decides to create multiple ORGs, where the name starts varying after the 49th char, only.

**Comment by jimmykarily** [comment]
Another way to go would be to rename `orgs` to `namespaces` and stop pretending they are anything other than that. Then we could simply say "namespace already exists" without implying it's a namespace where applications are deployed. Depending on how we implement authorization in the future this may be a good thing. E.g. if we define Epinio user permissions as native kubernetes RBAC rules then there is no need for an abstraction (e.g. `orgs`). If we do a custom thing, then maybe it makes sense to handle Epinio namespaces as a special kind.

**Comment by jimmykarily** [comment]
See also #544 and #611

**Comment by kkaempf** [comment]
Fixed via #544
