### ISSUE TITLE
Epinio registry is secured with TLS

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#440]
This is a follow up of #130

The registry to which the Tekton pipeline is pushing the application images should be accessed over TLS (by all consumers). Right now Tekton pushes images there and kubelet pulls them.

## Acceptance Criteria

- Tekton accesses the registry with mTLS (linkerd mesh). See finding on #130 regarding `linkderd tap` and non-http protocols.
- Kubelet accesses the registry with a Traefik ingress (publicly accessible). That ingress get's either a self signed cert or a production let's enrypt one. This is similar to how TLS works for applications.
- [investigation needed] The registry should be accessed using credentials. Those could be Traefik provided basic auth or the ones provided by the registry image itself (the ones that we already have). Whichever the case, no-one should be able to pull images from the registry without credentials.

**Comment by rohitsakala** [comment]
Progress

- Started understanding the various certificates we create in tekton and registry.
- Realised we create `registry-tls-self-ca` and `registry-tls-self` signed by `registry-tls-ca` by quarks-secret. The `registry-tls-self-ca` is then mounted on `tekton-staging` pod for it recognise `registry-tls-self` certificate in the case of tekton contacting registry for pushing the image. 
- The SSL termination happens in `ngnix` container in registry pod.
- Removed a function which creates a `service-account` and `registry-tls` certificate creation since they are not used anywhere. 

Questions

- Do we need Nginx for SSL termination now since we use linkerd? I suppose we don't. So have to remove Ngnix and whole `registry-tls-self` certificate generation.

Implementation Required

Production

- Ensure we have ingress for registry and create a production certificate when the domain is used.
- Kubelet to Registry is secure since it happens through HTTPS. Docker uses HTTPS by default.

Locally

- Ensure we have a self-signed certificate like we do for Nginx and make sure the `CA` is trusted by kubelet or write code in epinio to ensure all nodes of the kubernetes clusters trust the CA. Need to investigate here.
