### ISSUE TITLE
Split traefik installation to a separate command

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#477]
## Why

Controlling epic #488 

Because when we install Epinio on a public cloud provider, before we let the cert-manager do the self test (for the http challenge in the case of custom system-domain), we need to be sure that the system domain resolves to the traefik load balancer IP address. Otherwise, the failed DNS response will be cached and even if the user fixes the DNS later, they cert-manager will keep failing. This will prevent it from creating a let's encrypt certificate.

For public cloud providers that support LoadBalancerIP a better option is the provide the --traefik-loadbalancer-ip flag in `epinio installation` (#476)

## How

The user may or may not want to install traefik. We already provide a way to skip it, but no
way to install it separately. We will replace the `--skip-traefik` flag of the `epinio install`
command, with a separate `epinio install traefik` command (name of command to be discussed).

This new command will install Traefik on the cluster and wait until it gets and IP address.
If no IP address appears until the timeout, the command will fail with an error.

We document that a System Traefik, or a user's custom Traefik will not be part of the Linkerd mesh.
Only the Traefik handled by epinio itself will be.

## Flow

1. The user installs Traefik with this new command
2. The user creates a DNS A record pointing their custom system-domain to that IP address
3. The user installs Epinio with `epinio install --system-domain mydomain.org`

## Notes

The quick start configuration may be affected, depending on the cluster foundation.

1. With `k3d` as foundation nothing changes in terms of user commands, nor internally, as k3d supplies its own Traefik, and Epinio foregoes installing its own. Now it simply never installs it automatically.
2. Effects are unknown for other foundations, like `minikube`, `KinD`, etc.

**Comment by andreas-kupries** [comment]
@jimmykarily Question ... How does Traefik installation interacts with Linkerd ?

IOW, the full installation currently deploys Linkerd before Traefik.
Implying that Linkerd is needed when Traefik gets installed ?!

I hope that it is not, because then I can simply install Traefik and not care about Linkerd.
Otherwise we have to deploy Linkerd in both new `install-ingress` and regular `install`.
And the latter has to check for Linkerd presence to not try a second deployment.

**Comment by andreas-kupries** [comment]
Notes:
  - Traefik is currently in the mesh.
  - Therefore linkerd has to be deployed first
  - Because linkerd can only intercept new pods during their creation. It cannot inject itself into runing pods. Even if they are annotated
  - This implies that any kind of Traefik installed before epinio (k3d system traefik, user's custom traefik) will not be in the mesh.

For this ticket it means
  - Deploy Linkerd with `install-ingress`.
  - Check for linkerd presence in `install`, deploy if not present.

**Comment by manno** [comment]
>     * This implies that any kind of Traefik installed before epinio (k3d system traefik, user's custom traefik) will not be in the mesh.

You can restart the deployment, so it will be added to the mesh, I think?

**Comment by andreas-kupries** [comment]
System traefik is likely not annotated for linkerd, right ?
Neither a user's custom traefik ?

Restarting the deployment would apply only to the epinio traefik, right ?

So ...
  - Deploy traefik
  - Do all the DNS stuff we are separating things here for
  - Deploy epinio (with linkerd)
  - Redeploy traefik

This begins to feel like epicycles on epicycles on ...

**Comment by andreas-kupries** [comment]
Continuing this for now ...

On the issue of needing Traefik to be part of the Linkerd mesh or not, see the new ticket #489 to investigate.
