### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#486]
We should likely support multiple users per Epinio installation. It would be nice to allow a team to share a cluster if desired

This does not necessarily mean that there needs to be any mapping between orgs and users (or any additional access controls)

**Comment by kkaempf** [comment]
Upgrading to 'Beta'

- it's about authentication, not authorization (Rancher model: Use another cluster if you need to separate rights)

**Comment by agracey** [comment]
I have one technical request if it's at all possible. The list of users (and their creds) should be controllable via k8s objects. 

This would allow me to make similar integrations with Fleet as I did with services!

**Comment by agracey** [comment]
Also, I wonder if there's a way to have a ServiceAccount per Epinio user? That way we can work nicely with 3rd-party k8s auditing and compliance tools

**Comment by jimmykarily** [comment]
It would be nice if we could implement AAA using Kubernetes native things (ServiceAccounts/Users/RBAC). In case we can't, I found this: https://www.keycloak.org/
I imagine there are more alternatives like this out there. Another options could be to use Gitea for AAA as it was the original plan though I would only do that if Gitea is better than the alternatives for this duty. Being there doesn't mean we need to use it for everything.

**Comment by jimmykarily** [comment]
The problem with using Kubernetes RBAC for Epinio AAA is that:

- Users talk to Epinio through the Epinio API. This means Kubernetes authentication is irrelevant (they don't talk to the kube API). We need to find a way to identify an Epinio API user as a Kubernetes user and then a way to ask Kubernetes RBAC about this user's permissions.
- Any permission we grant to the user need to relate to some resource that has a mapping to one or more Kubernetes objects, otherwise it can't be defined in Kubernetes RBAC. E.g. You can't arbitrarily ask "can the user create an ApplicationConfiguration?" unless `ApplicationConfiguration` actually maps to real objects known to Kubernetes. I can't think of something we have currently that doesn't have a mapping but it may be a limiting factor for the future. On the other hand, we do want everything to have a mapping so this may be a good thing after all.

**Comment by jimmykarily** [comment]
Relevant docs: https://kubernetes.io/docs/reference/access-authn-authz/authentication/

**Comment by jimmykarily** [comment]
One idea would be to let the Epinio user authenticate with the Epinio API by passing all the information needed to act as an existing Kubernetes API user on the server side. A simplified PoC version of this would be to send the whole kubeconfig file to the server and whenever the Epinio server needs to do something on Kubernetes, it does so using the passed kubeconfig (warning: sometimes kubeconfig files are not transferable, they use local binaries to do auth, e.g. gke does that with gcloud cli).
In this simplified example, if the user is not allowed to do something on the kubernetes cluster directly, they won't be able to do that through Epinio either.

This means every user would potentially have access to the cluster directly if they ever wanted that. Their permissions would still be the same even if the took actions against Kubernetes, bypassing Epinio. This is not necessarily a bad thing.

Another potential issue is that Epinio API will only fail when a request against the Kube API is made (e.g. if the user is not allowed to do that). Any code before this request is made, will still run, because Epinio has way to check if the request is even made by a real Kubernetes API user or not. A way to solve this may be to have a Custom Resource (e.g. EpinioAPIAccess) which we try to `GET` as the very first step, when accessing the API. If that fails, then the request doesn't have a valid user.

The above are just brainstorming notes. They need more thought.

**Comment by agracey** [comment]
My suggestion (if it makes sense) is to solve the AuthN first then solve the AuthZ in a future ticket. 

Since we are using Traefik, we can use it's middleware to tie authN to something like Dex via it's annotations/labels. It has a few options of how to attach middleware but could solve the "hook into enterprise IDP" by making it not our integration to maintain. 

Then, a way to solve the AuthZ might be to use the user/group info sent by the middleware to select the ServiceAccount to use in the pipeline. I think there's a way in the K8s API to ask "can this SA perform this action" so you could do that prior to uploading code (the new step of creating the App prior to code upload would be a good place to put this logic)


I can draw a diagram of what I'm thinking after my morning meetings if you want.

**Comment by jimmykarily** [comment]
This may be useful: https://github.com/dexidp/dex

**Comment by jimmykarily** [comment]
Comparing dex with keycloak, dex can only act as a proxy for upstream Identity Providers (idp), while keycloak can work standalone or as a broker (https://www.keycloak.org/docs/latest/server_development/index.html#identity-brokering-apis). To use dex, we need to find an "upstream" provider that will be there by default. It supports gitea (https://dexidp.io/docs/connectors/gitea/) so that's one option. It would probably mean we have to expose the gitea interface again though.

**Comment by kkaempf** [comment]
Hmm, since we discussed about getting rid of gitea before, we should probably avoid going down that road.

**Comment by jimmykarily** [comment]
[Dex example](https://dexidp.io/docs/getting-started/#running-a-client) describes how to connect with a "local" username/password. Dex seems to support some kind of "local" database: https://github.com/dexidp/dex/blob/master/server/server.go#L571-L573

Worths investigating, I can't find much in the docs.

**Comment by jimmykarily** [comment]
Working branch: https://github.com/epinio/epinio/tree/486-multiple-users-dex

**Comment by jimmykarily** [comment]
Short update: The working branch now deploys dex and traefik-forward-auth and wires them together. There something wrong with the redirections though and it ends up in a login loop. We managed to get the whole authentiction working when we deployed traefik forward auth manually with help (outside epinio), so we can fix this by comparing the 2 setups.

Even after that, the epinio cli still doesn't "understand" the new flow and need to be adapted so that it allow the user to authenticate.

**Comment by jimmykarily** [comment]
This story started as a spike, then became an epic and then the actual implementation. Given the spike is done and now we know what we are going to do (traefik-forward-auth with dex as default idp), I will close this and create followup stories.
