### ISSUE TITLE
Windows: Cannot handle ANSI terminal control for output colorization

### ISSUE THREAD

**Issue by gunamata** [epinio/epinio#494]
The characters are printed wrong on cmd.exe.

C:\>epinio install

←[34m🚢 Epinio installing...
←[0m
Configuration...
  🧭  skip-traefik: ←[35mfalse←[0m
  🧭  skip-linkerd: ←[35mfalse←[0m
  🧭  system_domain: ←[32m←[0m
  🧭  email_address: ←[32mepinio@suse.com←[0m
  🧭  user: ←[32ma7f36a3b8756de3f←[0m
  🧭  password: ←[32m558f1bbd2d8fbebc←[0m

←[34m🚢 Deploying Linkerd...←[0m

**Comment by andreas-kupries** [comment]
Right. The full sequence are like `\033[0m` and the like. ANSI terminal control sequences.
On unix terminals they colorize the output. The inivisible `\033` is the escape character.
The example at the beginning means `reset everything to plain output`.

We have to disable that for Windows, looks like.
We use the go package `github.com/fatih/color`.

**Comment by andreas-kupries** [comment]
Some investigation shows me that `fatih/color` should support Windows, by means of `mattn/go-colorable`.
Should be since 2017 after a first glance.

... for a first, upgrade from 1.90 to 1.12.0.
That brings in support for the environment variable `NO_COLOR`.
Simply setting that variable (any value) will disable colorized output.
This gives us a workaround when things go wrong.

**Comment by andreas-kupries** [comment]
See PR #498 for a possible fix.

Even if not a fix, it should make a workaround available (Support for environment variable `NO_COLOR`. Setting it (to any value) should disable colorization.

**Comment by andreas-kupries** [comment]
A question: What version of Windows is this ?
