### ISSUE TITLE
Discussion: Replace AppCRD with our own

### ISSUE THREAD

**Issue by manno** [epinio/epinio#513]
AppCRD looks abandoned, last commit in 2020.

* Lot of fields that are not useful to us
* We can't extend it with our fields, like stage history, git repo creds
* No versioned client for use to use
* Uses old v1beta1 CRD format, not v1

**Comment by agracey** [comment]
I assume OAM is significant overkill for our needs?

**Comment by andreas-kupries** [comment]
OAM ? Unable to parse this TLA ...

**Comment by agracey** [comment]
Open Application Model: https://oam.dev/

**Comment by andreas-kupries** [comment]
I suspect that you are correct in assuming that this is overkill for us.

**Comment by jimmykarily** [comment]
Currently we don't use the controller and only use the CRD as an abstraction to "hang" resources on it. E.g. when we want to define env vars on an application that hasn't even been pushed yet. It doesn't really matter what the CRD looks like for this use. Let's stick to AppCRD (because we already have that) and if we need more from it in the future we can discuss replacing it. Closing.
