### ISSUE TITLE
bindings_test flaky

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#529]
This test:

https://github.com/epinio/epinio/blob/main/acceptance/bindings_test.go#L34

Sometimes it's not run at all:
https://github.com/epinio/epinio/runs/2885340957?check_suite_focus=true

some times it's green:
https://github.com/epinio/epinio/runs/2885077732?check_suite_focus=true#step:12:955

and some times it fails:

https://github.com/epinio/epinio/pull/526/checks?check_run_id=2885573423#step:12:1136

```
 [4]         
[4]         ✔️  Epinio Applications:
[4]         |      NAME      | STATUS |                     ROUTES                     |     SERVICES      |
[4]         |----------------|--------|------------------------------------------------|-------------------|
[4]         | apps-216083207 | 1/2    | apps-216083207.192.168.64.3.omg.howdoi.website | service-216084817 |
[4]         
[4]     to match regular expression
[4]         <string>: apps-216083207.*\|.*1\/1.*\|.*service-216084817
```

Should the app have 2 instances?

**Comment by andreas-kupries** [comment]
I suspect that the `not run at all` is a mis-look.
Going to the linked logs and searching them for `binding_test` shows that it was run, and it was green.

**Comment by andreas-kupries** [comment]
Attempted to replicate locally, running the tests focused on `bindings_test.go`.
Four attempts. Twelve runs per attempt.

Each attempt used less timeout for the `Eventually` than the previous.
1. 1min (unchanged compared to repo)
2. 30s
3. 10s
4. 1s
5. 0s

While the test flaked two times in attempts 1-4 none were due to `Eventually` timing out, it was always something in the setup or teardown.

In attempt 5 it flaked twice with the issue reported.

I strongly suspect that the issue seen in CI was a load spike on the action runner (VM (host)) slowing cluster operations extremely enough to run into the timeout. It should be a rare thing.

Best bet for a "fix" right now is to blindly increase the timeout to `5min` to overcome even the slowest operation of the cluster used by the action runner.
