### ISSUE TITLE
Declarative Install of Epinio

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#556]
Some users will want to use a solution like Fleet to install Epinio onto multiple clusters

**Comment by manno** [comment]
https://github.com/rancher/fleet-examples/

**Comment by agracey** [comment]
The suggestion from @manno to run `epinio install` from inside a pod is a fine way to do this. We just need to document the process of getting the first log in.

**Comment by manno** [comment]
I just became very good at repeating things Dimitris said once ;)

**Comment by jimmykarily** [comment]
Here is the PoC of that idea: https://github.com/epinio/epinio/tree/helm_chart . Does this qualify for "declarative install". If yes then we can revive it.

Do we want to support the "binary installation" too or completely switch to helm?

**Comment by agracey** [comment]
I think supporting both is good since we shouldn't assume knowledge of helm. 

I think some work into idempotency of `epinio install` can make this more stable going forward.

**Comment by agracey** [comment]
I think the better question is what will be easier to support upgrades and maintenance with?

**Comment by jandubois** [comment]
I think a declarative install via `helm` has major advantages when something doesn't work: you can see what is supposed to happen, and you can compare things. And most importantly, you can tweak the declaration and see if that fixes it.

Installation via a compiled setup program is great as long as everything works. But if the install fails, you are effectively stuck, unless you want to figure out how the setup program works, how it is compiled, etc. So the barrier for users to debug problems themselves (or extend the setup to a configuration not anticipated by the program developers) is huge.

Kind of like developing software via buildpacks, which is also great as long as everything is supported by the buildpack and works as expected. 😄

**Comment by jimmykarily** [comment]
The declarative install we have in mind right now, it mostly a wrapper around the "compiled setup program", I'm not sure if that cancels the benefits you describe @jandubois. Unfortunately, helm doesn't have a way to implement logic like:

"apply this yaml only when that other yaml has been applied" or "wait until a secret has appeared before you apply this yaml"

One would think that simply choosing the right installation order would solve the problem but it doesn't. Sometimes Kubernetes doesn't act like it should. For example, applying a yaml that defines a CRD doesn't mean you can immediately create a Custom Resource for it (https://github.com/epinio/epinio/blob/main/helpers/kubernetes/cluster.go#L277-L281).

Even worse, upstream components don't always implement the readiness probes correctly. This means, you can't rely on something being kubernetes-ready and you need hacky workarounds (https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L192-L216).

Generally, our binary evolved to act like a human would (retry if something wasn't ready, check the status of a component before you install something that depends on it etc). We were hoping that [hypper](https://hypper.io/) would solve some of these problems, and in a way it did, but not all of them.

I think a good plan is:

- For v1, support a declarative installation that wraps the same compiler binary. This allows the user to define all options in a yaml file instead of command line arguments. The user can re-apply the same configuration easily this way.
- For v2 (in a future far far away), evaluate the state of things (upstream tools, state of the epinio installer etc) and try to come up with a solution that is less hacky.

**Comment by kkaempf** [comment]
Based on current customer feedback, I'd focus on _application installation_ instead of _Epinio_ installation for now. Removing from Icebox.

Maybe we get more feedback once Beta1 is out.

**Comment by agracey** [comment]
@kkaempf I disagree. From the customers that I've talked to, the declarative install of the platform is equally as important. 

Also, we must be able to install through helm to get into the Rancher marketplace

**Comment by kkaempf** [comment]
Then we should select one of

* declarative install of Epinio
* declarative install of Applications

for Beta 2 in order to focus. 😉

**Comment by jandubois** [comment]
> The declarative install we have in mind right now, it mostly a wrapper around the "compiled setup program", I'm not sure if that cancels the benefits you describe @jandubois.

Yes, that cancels many of the benefits I see in declarative installs. It doesn't cancel the benefit @agracey is looking for though: inclusion in Rancher marketplace.

I have no opinion myself on relative priority; I think that should be driven by user feedback. 😄

**Comment by agracey** [comment]
We can discuss this further next week in the beta 2 planning call but my suggestion is to push to Beta 3 and have the focus of that release be on integration of the install, upgrade, and maintenance into Rancher. I think it's appropriate to say that users who want a better maintenance story can use Rancher to get those improvements.

**Comment by agracey** [comment]
Closing in favor of #810
