### ISSUE TITLE
Default installation fails late, if magic DNS isn't working - no fallback, no error

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#652]
If one follows the default installation `epinio install`, the installation will configure a system DOMAIN by using

\<traefik-public-IP\>.omg.howdoi.website

If the magic DNS service isn't working, the installation will fail at the end, e.g. when trying to access the API.

However, if the magic DNS service would work, could have been checked with a test IP even before we start the installation.
One thing to consider is, we most likely should check that from within the kube cluster, and not, or not only from the host that runs epinio/kubectl.

However, we should check if e.g. `10.0.0.1.omg.howdoi.website` resolves to `10.0.0.1`, before we start installing epinio, and if not, just error out before installing anything, or clean up with what we started with.

In addition, it could make sense to have other magic DNS services as fallback - so e.g. we could test and configure

10.0.0.1.nip.io (\<traefik-public-IP\>.nip.io), and/or
10.0.0.1.xip.io (\<traefik-public-IP\>.xip.io)

as fallbacks, if the preferred one doesn't work at install time.

**Comment by jimmykarily** [comment]
Our magic DNS is just a convenience for demos and development. We shouldn't create features in Epinio around `omg.howdoi.website`. Also any check that the system domain resolves to some specific IP address could lead to problems if there is networking that we don't take into account (proxies, load balancers etc). For example, once I used the `loadbalancer-ip` flag on the minikube installation with a domain that didn't resolve to the traefik IP address (the one from the flag), but resolved to the VMs "floating" IP (had ports forwarded and all). That resulted in an error, because we have a check to see if they match. My setup would have otherwise worked, it's just that Epinio tries to be smart and fails.

I will close this. Please open if you think I missed something and we should discuss more. Maybe we can convert it to a discussion then.
