### ISSUE TITLE
'--no-colors' option has no effect on Windows

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#673]
Passing the `--no-colors` command line option to Epinio on Windows has no visual effect.

**Comment by andreas-kupries** [comment]
Which terminal are we speaking about here ? cmd.exe, or the git bash ?
Which commands were tried ? (Not all commands have colorized output)

**Comment by kkaempf** [comment]
This happens in PowerShell. I only tried `install` and `uninstall` so far. Both are cluttered with escape sequences.

**Comment by andreas-kupries** [comment]
Hm. Ok. Will see what my win 10 VM says ...

**Comment by andreas-kupries** [comment]
Set up a cross-machine scenario, because I still can't get RD to work on the Win VM.
So, Windows Epinio client for a linux-based cluster.
Do to the domain issue (omg) I used `epinio config show` and `epinio config show --no-colors` as test commands.
These do not talk to the server, and do colorized output.

|Command |Git Bash|`cmd.exe`|Power Shell|
|---|---|---|---|
|`show`| :heavy_check_mark: | :boom: | :boom: |
|`show --no-colors`| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

For colored output the :heavy_check_mark: means that the output was colored, whereas :boom: indicates a mess of uninterpreted escape sequences. For uncolored output :heavy_check_mark: means that the output was indeed not colored, whereas :boom: indicates a mess again.

The `show --no-color` was ok in all shells, no mess at all.

IOW, I am unable to confirm the descriptions.

Below a screenshot showing the results for all the shells (Power Shell top left, `cmd.exe` top right, git bash below in the background, partially covered, but not enough to not see the colored output)

![VirtualBox_EWT_11_08_2021_16_20_40](https://user-images.githubusercontent.com/577247/129047354-a6f2cc0f-e5e7-4846-ab28-c81232d6c08b.png)

**Comment by andreas-kupries** [comment]
The only messes I see are the emoji characters, these are not handled by neither `PS` nor `cmd`, only git `bash`.

**Comment by kkaempf** [comment]
I can confirm that running `epinio config show --no-colors` indeed behaves correctly.
However, `epinio uninstall --no-colors` clutters the output with ESC sequences.

**Comment by andreas-kupries** [comment]
Ok. Will look into that. It seems then that `uninstall` is not hooked to the color controls ... And you said `install` also has the issue, before, so I guess it is the `install_client` structure and methods as the shared point for both.

Thanks.

**Comment by kkaempf** [comment]
There's also [this stackoverflow question](https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes) explaining the handling of ANSI sequences in PowerShell.

**Comment by andreas-kupries** [comment]
Hm. I believe the issue should be repro'able for Linux also, i.e. `--no-colors` without effect. Just no mess ... Will check that ... If true testing a fix should be much easier.

**Comment by andreas-kupries** [comment]
The SO answers are interesting. Will have to check the underlying go package to see what it does wrt this, if anything.

**Comment by andreas-kupries** [comment]
Yes. The color controls come in through loading epinio's config when creating the `Client`.
This is done because the color choice is not just via `--no-colors` and assorted EVs, but also a config element.
Loading the config merges all these sources into a single result.

And the `InstallClient` does not do that. Assumes that the config does not exist or does not matter.
Will see how much breaks if I try to load it here too.

**Comment by andreas-kupries** [comment]
Extended #671 with fix for this.

**Comment by andreas-kupries** [comment]
Our underlying package is [mattn/go-colorable](https://github.com/mattn/go-colorable). The [relevant code](https://github.com/mattn/go-colorable/blob/master/colorable_windows.go#L109) seems to activate the necessary processing.

That this does not seem to happen for us ... Maybe the controlling [isatty.IsTerminal()](https://github.com/mattn/go-colorable/blob/master/colorable_windows.go#L107) condition returns an incorrect value ?

**Comment by andreas-kupries** [comment]
Falsified. Latest #671 [commit](https://github.com/epinio/epinio/pull/671/commits/aa187a20108498ef91712d7764c84cb355a63d8a) added command to introspect the tty, using the `mattn/go-isatty` package, same as used by `mattn/go-colorable`.

See the 
![screenshot](https://user-images.githubusercontent.com/577247/129198305-fd5393d9-7dba-4e77-a358-a4bbf9d74927.png)

**Comment by andreas-kupries** [comment]
Setup
  - Platform: Win 10 Home (Virtual Machine, Linux-hosted, VirtualBox)
  - Modules (`grep 'fatih\|mattn' go.mod`):
      - github.com/fatih/color v1.12.0
      - github.com/mattn/go-isatty v0.0.12
  - Sum Modules (`grep 'fatih\|mattn' go.sum |grep -v go.mod`):
      - github.com/fatih/color v1.12.0 h1:mRhaKNwANqRgUBGKmnI5ZxEk7QXmjQeCcuYFMX2bfcc=
      - github.com/mattn/go-colorable v0.1.8 h1:c1ghPdyEDarC70ftn0y+A/Ee++9zz8ljHG1b13eJ0s8=
      - github.com/mattn/go-isatty v0.0.12 h1:wuysRhFDzyxgEmMf5xjvJ2M9dZoWAXNNr5LSBS7uHXY=
      - github.com/mattn/go-runewidth v0.0.7 h1:Ei8KR0497xHyKJPAv59M1dkC+rOZCMBJ+t3fZ+twI54=
    Without excluding `go.mod` lines I see a lot more versions for all the packages.

**Comment by andreas-kupries** [comment]
Upstream ticket is mattn/go-colorable/issues/58

**Comment by kkaempf** [comment]
Confirmed, `install` and `uninstall` have a readable (though colorless) output now.

**Comment by andreas-kupries** [comment]
Note, to check for working `--no-colors` use `epinio config colors true` first, to simulate a setup with colors active, which then can be suppressed by the option.

**Comment by kkaempf** [comment]
The patch suggested by upstream only partially fixes the color output. All boolean values from `config show` are displayed blank, also the dots are missing from the `install` output.

**Comment by kkaempf** [comment]
Building from the latest patch (fix: mishandled non-portable color output.) of #671, the color output still has problems.
![colored-output](https://user-images.githubusercontent.com/37742/129229736-e059085f-965d-42f4-b1e9-d9b4a30d9abf.jpg)

While 'cmd.exe' shows the `true` for "Colorized Output", it shows as blank in PowerShell.

Same for the initial configuration display of `epinio install`. None of the boolean values are displayed:
![colored-install](https://user-images.githubusercontent.com/37742/129230123-4ee69698-c987-442f-b7f9-a0bf5183fd59.png)

**Comment by andreas-kupries** [comment]
No. Change the background color of the powershell. The color we use for the dots and bools looks to match. With a different background it should be visible.

**Comment by kkaempf** [comment]
Do we use different color depending on the shell ? The `true` for "Colorized Output" in cmd.exe above is purple. This color should be visible on a blue background !?

**Comment by andreas-kupries** [comment]
No. It is all `Magenta()` to us. I suspect that PowerShell has different RGB mappings for the various names.
Tempted to write a `debug colors` command (See the `debug tty` command I added) to simply show all the colors available.
Then we can properly compare the shades in the different terminals set to a white background.
