### ISSUE TITLE
[Spike] oauth2 + oidc + dex research

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#686]
Let's try to understand a bit more about how oauth2, traefik forward auth and dex work before we try to implement a solution.

**Comment by manno** [comment]
We discussed this and decided to not move forward with OIDC.  Instead we will try to build upon the basic auth middleware from Traefik that we already use.
We hope that, in the future we can easily change the Epinio CLI to use different kinds of credentials. That would allow us to ship with the basic auth middleware solution by default, but support more complicated setups.

One such setup could be the ForwardAuth middleware from Traefik, together with a ForwardAuth compatible auth server, like https://github.com/thomseddon/traefik-forward-auth/. That server would make authorization requests to Dex, which acts as an OpenID Connect provider/forwarder.
That setup was partially implemented, but reverted in PR https://github.com/epinio/epinio/pull/675.

So for now we want to:

* use header fields in the server to get more information about the request, like the user's name
* extend the client to be able to send a token instead of the basic auth header
* (later) evaluate what kind of auth setup we would need, how much work has to be done in the CLI (redirect flow, just token), which parts should be modular (keycloak, dex), how to integrate with existing user systems (Rancher)
