### ISSUE TITLE
Epinio created resources are tagged with a user

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#707]
Depends on #706

Since we now know who the user is in the Epinio server, we can start adding some annotations on the various resources we create

## Acceptance Criteria

- When an app is pushed successfully, the App CRD user field gets updated with the user that did the push
- PipelineRuns have an annotation set to the user that triggered the staging
- Services are annotated with the user that created them
- [Optional] Any command that shows a resource (e.g. `epinio app show`) shows the user that created it.

**Comment by andreas-kupries** [comment]
FYI #718 is the PR showing how the user information is provided to the server, and how it can be extracted server side.
In the referenced PR this extraction happens only in the request log handler, so that it can be put into the log.

For this issue the extraction has to be also done in all the request handlers themselves who have to know the user so that they can insert it into the resources they create.
