### ISSUE TITLE
Make CI (all Badges) green - and stable

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#757]
We released e.g. epinio 0.0.24, while most badges in the README are red. While general CI might have been green for the release, others were red.

In addition, I today failed with installing epinio (v0.0.23 and v0.0.24) on e.g. EKS.

**Comment by manno** [comment]
CI reports this error: 

```
🚢 Create Custom Service
  Name: service-23503500
  Namespace: 
  | PARAMETER |  VALUE  |
  |-----------|---------|
  | mariadb   | 10-3-22 |
  error creating service: invalid character 'M' looking for beginning of value
```

By slightly modifying the error reporting, I can see the actual error: 

```
error creating service: cannot parse JSON response: Method Not Allowed
: invalid character 'M' looking for beginning of value
```

Trace logging shows the outgoing request from the CLI: `EpinioClient "level"=1 "msg"="POST https://epinio.aks.example.com/api/v1/namespaces//custom-services"`.

However the server's logs show: `"msg"="received request"  "method"="GET" "uri"="/api/v1/namespaces/custom-services"`.

How did the POST end up as a GET? We renamed the 'orgs' endpoints to 'namespace' and ended up with these rules:

```
	"OrgDelete": delete("/namespaces/:org", errorHandler(OrganizationsController{}.Delete)),
	"ServiceCreateCustom": post("/namespaces/:org/custom-services", errorHandler(ServicesController{}.CreateCustom)),
```

Now, the request has a double slash in `namespaces//custom-services`, because the test setup did not target a namespace. Our router probably matches the URL to `delete("/namespaces/custom-services")` and detects the method does not match.

**Comment by manno** [comment]
I'll have to wait for the scheduled workflows.
