### ISSUE TITLE
Installation, Maintenance, and Upgrades through Rancher

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#810]
This is a replacement of #556

We need to allow for easy installation of Epinio to Rancher users using nothing but the Rancher UI. This is probably best done using the Epinio UI addon that's currently being developed. 

**Describe the solution you'd like**
I would like to be able to install Epinio onto clusters managed by the Rancher UI through the Epinio plugin. I would also like to eventually configure and update the installation through the same UI. 

**Describe alternatives you've considered**
We could wrap the `epinio install` command with a pod and run it in a Job through helm but that seems very "hacky".

**Comment by jandubois** [comment]
Just an example of the issue I have with install programs. @prabalsharma attempted to install Epinio on the latest Rancher Desktop, but it failed. Even with verbose logging, all we get is:

```
🚢 Creating namespace...
Name: workspace
error creating namespace: All attempts fail:
#1: request cancelled or timed out
```

This is utterly useless, as it doesn't include any information to figure out what is wrong, and what the user could do to fix it.

It is obviously not a problem with creating namespaces per-se, as earlier the log included

```
🕞  Waiting for namespace tekton-staging to be appear 
```

and that didn't cause any error. And all the pods are running fine in their various namespaces as well.

With a helm chart we would be able to see which commands are be executed, what the errors are, and maybe try different things to work around the issue. But with an opaque install program all we can say is:

> Looks like a bug in Epinio; contact the developers and let them take a look. For now you are out of luck; there is no workaround. Hope they get back to you soon!

<hr>

I know this is all a matter of priorities, and I'm just writing this here to illustrate my point, not asking you to reprioritize!

**Comment by jimmykarily** [comment]
We tried various ways to stay as close to "just helm" as possible. It turnes out that there are certain things helm simply can't do. I won't repeat it all here but the most important is that you can't define order and dependencies among multiple charts. Subcharts were made with a different use case in mind, no order can be forced.

The result is described here: https://github.com/epinio/epinio/issues/987#issuecomment-992215187
So, if you go the manual way, you deploy the various components yourself and you better understand what's going on. If you use the "beginner's helm chart" that does everything for you, a binary installer will be used because there is no other way around it.

I will close this issue because it's been split into multiple stories with most of them already implemented:

- 2 different helm charts exist now
- There is a way to use them from within Rancher to install Epinio
- Upgrades are being worked on but they will come in the form of `helm upgrade` of the epinio (small) helm chart.
