### ISSUE TITLE
CLI - Show `flag` value when viewing config values

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#864]
**Is your feature request related to a problem? Please describe.**
It's not immediately obvious what the `flag`s are when executing `epinio config update`. Inherent knowledge of the config file is needed

**Describe the solution you'd like**
`epinio config show` could be updated to also show a `flag` column. Help output for `epinio config update` to include where to find flags

**Describe alternatives you've considered**
Help output for `epinio config update` could direct user to view `Config` file for `flag` values

**Comment by andreas-kupries** [comment]
Hi @richard-cox 

We have trouble understanding the request/ticket.

Looking at the output of either `epinio config update` or `epinio config show` I see now references to `flags`.
For `show` the output refers to keys and values, is that what you mean ?

Looking a bit further afield, I do see `... [flags] ...` mentioned in the `--help` output for these commands.
However these flags are then immediately explained underneath the command description, for command specific and global flags/options.

Could you be somehow thinking that the `update` command's flags control what part of the config is updated ?
Because, no, there are no such flags. `config update` always updates the entire config with the information it can pull form the targeted cluster.

**Comment by richard-cox** [comment]
@andreas-kupries You're right, I incorrectly assumed that `config update` was for changing specific values
