### ISSUE TITLE
The `epinio install` command should quickly fail if the environment doesn't fulfill the requirements

### ISSUE THREAD

**Issue by catherineluse** [epinio/epinio#883]
When I was installing Epinio on RKE2 and RKE, I got the error message:

```
error installing Epinio: timed out waiting for LoadBalancer IP on traefik service
Ensure your kubernetes platform has the ability to provision a LoadBalancer IP address.
```

The error came at the end of the installation process. I think the user experience would be better if Epinio would quickly fail if the installation requirements aren't fulfilled because it would save some time.

**Comment by jimmykarily** [comment]
The ability to assign an IP to load balanced services is most of the time supplied by non-kuberentes components which Epinio can't inspect. In other words, Epinio can't know if a LoadBalanced service will get an IP address unless it creates one and waits to see what happens. You are right, the UX is not good here but that's merely because the cluster doesn't support LoadBalanced services properly. I can't think of a way to solve this.

**Comment by jimmykarily** [comment]
The new way to deploy Epinio is using the helm charts here: https://github.com/epinio/epinio-helm-chart
There no waiting happening anymore for the service to get an IP address. This issue can be closed.
