### ISSUE TITLE
Health checks for workloads

### ISSUE THREAD

**Issue by manno** [epinio/epinio#900]
Epinio creates deployments for the pushed apps.

Pods should have a health/ready/(startup) check.
Is the k8s default good enough?

What's the minimum we can do for apps. Should this be customizable, e.g. when an app implements a separate health check endpoint?
Some apps might need a startup probe, to make them wait before they start.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Example: https://github.com/workadventure-suse/workadventure-kustomize/blob/master/base/front-deployment.yaml#L88-L98

**Comment by andreas-kupries** [comment]
Ok. I am coming away from the above with the following acceptance criteria:

  - Implement support (manifest, options) for spec of app level probes. Like existing support (env, services, instances) it is optional. Defaults to `no probes`. Limit initial implementation to http probes and config (port, path, scheme). Future work can expand on the supported probe types, and other config (delays and thresholds).

  - Extend the code fetching app status to get the container statuses from all pods, excluding linkerd containers. Show the information in app show and list (compressed). Without probes (default) this data is likely not meaningful. Provide information about probe existence so that display code is able to make data from with/out probes visually distinct.

**Comment by andreas-kupries** [comment]
See doc draft PR https://github.com/epinio/docs/pull/18 for the specification of this new feature, as seen by a user.

**Comment by andreas-kupries** [comment]
Suspended

**Comment by agracey** [comment]
Let's keep this simple and allow for either a configurable paths for readiness probes or default to pid 1 detection. 

I don't think we need to allow http and port configurability as we know those (http/8080) for the vast majority of applications. 

We can always add functionality later if a customer asks.

**Comment by jimmykarily** [comment]
@agracey what if we allow the operator to specify probes on the App crd and we simply copy them over to the Deployment when we create it? This way we don't have to expose all the Kubernetes logic in the epinio cli but we still allow the advanced use to specify probes using the App crd (either manually or with a webhook/controller).

**Comment by agracey** [comment]
What we have is fine for beta 2. Let's get on a call late next week to look at what's possible later on.

**Comment by enrichman** [comment]
With a custom app chart you can define your readiness endpoints. Clsing.
