### ISSUE TITLE
Persist information on application deployment method

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#912]
Right now there is no way to tell how an existing application was deployed (staged from local code, container image or git).
This information is needed in the Web UI in order to decide wether to show a "restage" button or not. See here for more: https://github.com/epinio/ui/issues/10

This information should be part of the application API responses (list, get etc)

**Comment by andreas-kupries** [comment]
For a first attempt this could be stored in the `scale-secret`. That is secret currently contains a single key, `desired` whose value is the number of desired instances.

For the suspended app health support (#900) I saved the probe information into additional keys in that secret. And because the information was complex I minimized key usage by serializing the data to json and then storing the json string.

This is quite trivial, and for the deployment we already have the necessary structure carrying the information to (de)serialize from/to, i.e. `ApplicationOrigin`

**Comment by andreas-kupries** [comment]
First pieces of work - App CRD repo - https://github.com/epinio/application/pull/2
