### ISSUE TITLE
Support editing of a Service

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#982]
**Is your feature request related to a problem? Please describe.**
A user should be able to edit a service. In reality, at the moment, this would just cover the key-value data

**Describe the solution you'd like**
Support PATCH on `/api/v1/namespaces/<ns>/services/<service name>` 

**Additional context**
Related to https://github.com/epinio/epinio/issues/981, blocking UI issue https://github.com/epinio/ui/issues/9

**Comment by jimmykarily** [comment]
Make it a PUT and replace the old service data altogether? @agracey  If the user does that through the web UI the end result would be the same (since the old keys would all be in the sent form data) but through the cli, it means the user should provide all the keys every time.

**Comment by andreas-kupries** [comment]
Another likely `PUT` / `PATCH` difference: With `PUT` you can remove keys. With `PATCH` only if we model the ability into the request structure ... (Similar to the kube patches with op/path/value information).

Another issue to think about, how to represent that in the CLI.
I know that @richard-cox wants it for the UI, however just having this for the UI, and not the CLI strikes me as wrong.
So, to design for both

  1. `epinio service update name  key value ...`. like `service create`, except it would expect an existing service, and replace the existing key/value set with the new set. User has to provide all the desired keys, even if they do not change.
  2. `epinio service update name --remove key ... --set key-value ...` User can edit part of the service keys, including removal, without touching others (`--set` serves as both `change` and `add` operation).

Form 1 is essentially the `PUT` exposed. And form 2 the `PATCH`.

Form 1 above is nicer for the UI I believe. Because the UI shows all the keys, the user can then edit (add, remove, change) as desired, and at the end the new state commited en-block via PUT.

With form  2 the UI will have to keep track of exactly what is edited and how so that it con construct the change commands to apply. It needs a shadow structure for the current state the edited state can be compared to for patch construction.

On the other side, form 1 is not as convenient to a CLI user, due to having to re-specify the unchanged parts. Manually copying data from `service show` over. And form 2 is here the nice and easy case.

And as much as do not want to make more work for me ;) the best of all worlds may be to support both forms at the API level, and then each mode of operation (CLI, UI) uses what is best for them.

@richard-cox Your thoughts?

**Comment by thardeck** [comment]
The plan is to implement a second endpoint with PUT.
