### ISSUE TITLE
[Epic] Upgradeability - upgrade of Epinio

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#987]
**Is your feature request related to a problem? Please describe.**

This is marked as Epic/Spike to start research and collect ideas/approaches around upgrading.

Upgrade of Epinio
- while keeping settings
- apps run uninterrupted

Things to consider
- UI implications ?
- API changes (breaking / non-breaking)
- CLI option changes
- Helm chart deployment

**Describe the solution you'd like**

As a cluster admin, I can upgrade Epinio, without disturbing Epinio users (CLI & UI)

**Describe alternatives you've considered**
TBD

**Additional context**
TBD

**Comment by andreas-kupries** [comment]
[Upgrading.md](https://github.com/epinio/epinio/files/7562349/Upgrading.md)

Attached current state of thoughts and research.

**Comment by kkaempf** [comment]
@agracey 👆🏻

**Comment by agracey** [comment]
Thank you @andreas-kupries for looking into this.

A few thoughts:

- Do we really need to automate the upgrade of components that are optionally "bring your own" (Traefik, Linkerd, cert-manager, minio, registry)?
-  - Specifically, if we are accessing that component through a standardized API, there's little risk of drift being impactful and they can be upgraded outside of our automation. Maybe security patches would be important to force an upgrade but this can maybe still be manual.
- Upgrading Linkerd is likely not fully automatable. I did the upgrade from 2.10 to 2.11 and, while not bad, is a little more than we likely want to take on. 


Assuming we don't need to upgrade the underlying components, I think a similar but more granular flow might look like:
- Put API in readonly mode (or just turn off routing to the API)
- Wait for all pipelines to finish or be cancelled 
- Install new CRDs, tekton assets, and charts
- Migrate existing CRs to new spec
- Remove old CRDs, and other assets that need clean up
- Upgrade epinio deployment
- Restage workloads using new epinio API (could maybe even be optional?)
- Take API out of readonly

The key piece here is that some API downtime is fine but preferably not workload downtime.

As far as versioning goes, I think additive changes are fine in the same spec version but any deletions or structure change would require a version bump.

**Comment by andreas-kupries** [comment]
> Do we really need to automate the upgrade of components that are optionally "bring your own" (Traefik, Linkerd, cert-manager, minio, registry)?

It was my impression that `automatic upgrade of components` (`AUoC`) was part of the requirements for upgrading.
Maybe because `AUoC` was a true thing for the kubecf/CAP work. Where it not really worked out.
A great deal of complexity I was worried about goes away with `AUoC` is out of scope.

Re downtime - Yes, I was always considering `no workload downtime` as the requirement, not API downtime.
API downtime is something I am fine with. Should have made that clear.
Actually, in my head API downtime was always implied in the process, simply to avoid devs interfering with the process.
And definitely missing in my description of the big bad fallback process of `make a new parallel cluster`. That one would have API downtime only during the step where applications get copied over to the new cluster.

> additive changes are fine in the same spec

I believe that that should read `additive optional changes are fine in the same spec`. New mandatory fields are likely breaking. That said, having new fields optional in general should be easy, as long as the API server knows how to set the necessary defaults a mandatory field would have incurred. And in that round about way the original phrasing is sort of correct.

The core of your flow looks to be

> Install new CRDs, tekton assets, and charts
Migrate existing CRs to new spec
Remove old CRDs, and other assets that need clean up

Note that at the technical level there is always only a single CRD in the system. Just different forms of it.
Based on my reading of the kube docs you initiall have a CRD supporting version A.
`Install new CRD` replaces that with a CRD specifying and supporting versions A, and B. Both old and new.
And after the CR migration `Remove old CRD` then replaces that with a CRD supporting only version B.
So, not really installing/removing CRDs and more adding/removing supported versions to/from the one CRD.

I hope to not come across as too anal-retentive in the above.
The good thing about computers is that they do exactly as you tell them.
The bad thing about computers is that they do exactly as you tell them.
Given that I am trying to precise.

Migrating the CRs ... With the flow above migrating could be as simple as having the epinio server read all the app resources, and then update them, as that updates the stored version. I more complex scenarios the relevant client command could also incorporate the necessary logic to fill in new mandatory fields.

`Restage the workload` ... Not sure where that will be needed right now ... Maybe when linkerd is used, and used for meshing the workloads as well. Agreed as optional step in an upgrade flow.

**Comment by agracey** [comment]
Personally I believe AUoC can stay out of scope until a customer explicitly puts it in scope and gives a very good reason for it. 

I think we are on the same page re: API vs workload downtime. 

For CRD upgrades, that's some really good clarifications! 

My thought with the optional workload restage is if there's a change in buildpack or deployment template that a user would like to rebuild with. I guess that should just be a workload specific choice made after the upgrade completes?

**Comment by andreas-kupries** [comment]
> My thought with the optional workload restage is if there's a change in buildpack or deployment template that a user would like to rebuild with. I guess that should just be a workload specific choice made after the upgrade completes?

IMHO yes. The active workloads are running of images, i.e. are self-contained, not dependent on a separate runtime. As such if the user chooses to let an application running even if there are updates in a buildpack, etc., then they should be able to.

Ditto for changes in the deployment template. applies newly started apps, and restaged apps, does not affect a running app. such will simply keep using the old structure.

**Comment by jimmykarily** [comment]
Let me add one more alternative: https://github.com/epinio/epinio/tree/documentation-installer/helm/chart/epinio

The plan for #1006  could be to implement an installer framework, which is not Epinio specific but would allow us to implement those steps described in the linked README.

If that succeeds, we can remove all the installer code from Epinio itself. We will then provide 2 ways of installation:

- The "beginner" one, with the declarative installer (we will provide the manifest)
- The "advanced" one which is the manual process described in the helm chart.

The "beginner" installer doesn't necessarily have to support upgrades. It's meant to be used to quickly get Epinio up and running. You shouldn't need to upgrade such a setup. The upgrades of the "advanced" setup will probably look something like `helm upgrade epinio -n epinio`. Component upgrades can be documented (by us or upstream).

**Comment by kkaempf** [comment]
Not sure if the "advanced" install resonates well with Rancher customers.
The majority of "Rancher Marketplace" applications installs with a single click, possibly with some editable attributes.

Can a Rancher installation start with the "beginner" style install, autodetecting already present artifacts, and editable later ?
How is the relation between "beginner" and "advanced" ? Are both based on the same underlying code and install template ?

**Comment by jimmykarily** [comment]
There are 2 types things the current Epinio installer installs:

- Upstream components
  Epinio installs those in the simplest possible way. We only ensure the options Epinio needs are there. We don't support customization even if the underlying (upstream) helm chart supports it. This means, if a team wants to deploy cert-manager using some option we don't support in the Epinio installer, they are out of luck. We do have the `skip-*` flags that allow some flexibility but in the end, the process of installing those components will be manual.

- Epinio specific components
  These are the same both in the binary installer (current one) and the helm chart here. The "beginner" installer would be nothing but a binary implementation of the process in the README (based on a machine-friendly description, aka manifest, rather than a README).

One could use the declarative installer to install only some of the Epinio requirements by simply removing the rest from the manifest. Both ways would be supported and it costs us nothing more on maintenance than what we have now. 

A wrapper helm chart that calls the beginner/declarative installer is still an option but I think a plain helm chart for production level deployments is more important. Having both may create confusion to users.

**Comment by jimmykarily** [comment]
So after various discussions and experimentation, we now how 2 helm charts: https://github.com/epinio/epinio-helm-chart/tree/main/chart

the `epinio-installer` one, installs dependencies and Epinio, the `epinio` one installs just Epinio (and it's what the first chart uses to install Epinio as well). There is a PR to update docs: https://github.com/epinio/docs/pull/30 .
We can improve the charts and the docs but the plan is clearer now.

So the answer regarding upgrades of Epinio is that we will make sure the `epinio` helm chart can always upgrade smoothly as long as the appropriate version of the various Epinio dependencies are in place. Upgrading dependencies will be a matter of documentations. In some cases, it may by possible to upgrade using the `epinio-installer` helm chart. But this is not guaranteed and not a supported feature, at least, until there is user request for that.
